// Auto-generated by scripts/xbox/make_crafting_groups.py -- do not edit.
// Console crafting menu: tab and base type of each crafted item.
#pragma once

enum LegacyCraftingGroup : unsigned char
{
    LEGACY_CRAFT_STRUCTURE = 0,
    LEGACY_CRAFT_TOOL = 1,
    LEGACY_CRAFT_FOOD = 2,
    LEGACY_CRAFT_ARMOUR = 3,
    LEGACY_CRAFT_MECHANISM = 4,
    LEGACY_CRAFT_TRANSPORT = 5,
    LEGACY_CRAFT_DECORATION = 6,
    LEGACY_CRAFT_GROUP_COUNT = 7
};

// baseType 0 = none: the item gets a column of its own.
struct LegacyCraftingGroupEntry { short id; short aux; unsigned char group; unsigned char baseType; };

static const LegacyCraftingGroupEntry s_legacyCraftingGroups[] = {
    { 5, -1, 0, 18 }, // Tile::wood (structwoodstuff)
    { 5, 0, 0, 18 }, // Tile::wood (structwoodstuff)
    { 22, -1, 6, 13 }, // Tile::lapisBlock (block)
    { 23, -1, 4, 0 }, // Tile::dispenser
    { 24, -1, 0, 19 }, // Tile::sandStone (structblock)
    { 25, -1, 4, 0 }, // Tile::musicBlock
    { 27, -1, 5, 12 }, // Tile::goldenRail (rail)
    { 28, -1, 5, 12 }, // Tile::detectorRail (rail)
    { 29, -1, 4, 26 }, // Tile::pistonStickyBase (piston)
    { 33, -1, 4, 26 }, // Tile::pistonBase (piston)
    { 35, -1, 6, 16 }, // Tile::cloth (cloth)
    { 41, -1, 6, 13 }, // Tile::goldBlock (block)
    { 42, -1, 6, 13 }, // Tile::ironBlock (block)
    { 44, -1, 0, 21 }, // Tile::stoneSlabHalf (halfslab)
    { 45, -1, 0, 19 }, // Tile::redBrick (structblock)
    { 46, -1, 1, 0 }, // Tile::tnt
    { 47, -1, 6, 0 }, // Tile::bookshelf
    { 50, -1, 1, 22 }, // Tile::torch (torch)
    { 53, -1, 0, 15 }, // Tile::stairs_wood (stairs)
    { 54, -1, 0, 34 }, // Tile::chest (chest)
    { 57, -1, 6, 13 }, // Tile::diamondBlock (block)
    { 58, -1, 0, 29 }, // Tile::workBench (device)
    { 61, -1, 0, 29 }, // Tile::furnace (device)
    { 65, -1, 0, 0 }, // Tile::ladder
    { 66, -1, 5, 12 }, // Tile::rail (rail)
    { 67, -1, 0, 15 }, // Tile::stairs_stone (stairs)
    { 69, -1, 4, 0 }, // Tile::lever
    { 70, -1, 4, 14 }, // Tile::pressurePlate_stone (pressureplate)
    { 72, -1, 4, 14 }, // Tile::pressurePlate_wood (pressureplate)
    { 76, -1, 4, 0 }, // Tile::notGate_on
    { 77, -1, 4, 33 }, // Tile::button (button)
    { 80, -1, 0, 19 }, // Tile::snow (structblock)
    { 82, -1, 0, 19 }, // Tile::clay (structblock)
    { 85, -1, 0, 28 }, // Tile::fence (fence)
    { 89, -1, 1, 22 }, // Tile::lightGem (torch)
    { 91, -1, 1, 22 }, // Tile::litPumpkin (torch)
    { 96, -1, 0, 6 }, // Tile::trapdoor (door)
    { 98, -1, 0, 19 }, // Tile::stoneBrickSmooth (structblock)
    { 101, -1, 0, 28 }, // Tile::ironFence (fence)
    { 102, -1, 6, 0 }, // Tile::thinGlass
    { 103, -1, 2, 0 }, // Tile::melon
    { 107, -1, 0, 0 }, // Tile::fenceGate
    { 108, -1, 0, 15 }, // Tile::stairs_bricks (stairs)
    { 109, -1, 0, 15 }, // Tile::stairs_stoneBrickSmooth (stairs)
    { 112, -1, 0, 19 }, // Tile::netherBrick (structblock)
    { 113, -1, 0, 28 }, // Tile::netherFence (fence)
    { 114, -1, 0, 15 }, // Tile::stairs_netherBricks (stairs)
    { 116, -1, 0, 29 }, // Tile::enchantTable (device)
    { 123, -1, 4, 0 }, // Tile::redstoneLight
    { 126, -1, 0, 21 }, // Tile::woodSlabHalf (halfslab)
    { 126, 0, 0, 21 }, // Tile::woodSlabHalf (halfslab)
    { 128, -1, 0, 15 }, // Tile::stairs_sandstone (stairs)
    { 130, -1, 0, 34 }, // Tile::enderChest (chest)
    { 131, -1, 4, 0 }, // Tile::tripWireSource
    { 133, -1, 6, 13 }, // Tile::emeraldBlock (block)
    { 134, -1, 0, 15 }, // Tile::woodStairsDark (stairs)
    { 135, -1, 0, 15 }, // Tile::woodStairsBirch (stairs)
    { 136, -1, 0, 15 }, // Tile::woodStairsJungle (stairs)
    { 139, -1, 0, 28 }, // Tile::cobbleWall (fence)
    { 143, -1, 4, 33 }, // Tile::button_wood (button)
    { 145, -1, 0, 29 }, // Tile::anvil (device)
    { 155, -1, 0, 19 }, // Tile::quartzBlock (structblock)
    { 156, -1, 0, 15 }, // Tile::stairs_quartz (stairs)
    { 171, -1, 6, 37 }, // Tile::woolCarpet (carpet)
    { 256, -1, 1, 2 }, // Item::shovel_iron (shovel)
    { 257, -1, 1, 3 }, // Item::pickAxe_iron (pickaxe)
    { 258, -1, 1, 4 }, // Item::hatchet_iron (hatchet)
    { 259, -1, 1, 27 }, // Item::flintAndSteel (devicetool)
    { 261, -1, 1, 23 }, // Item::bow (bow)
    { 262, -1, 1, 23 }, // Item::arrow (bow)
    { 264, -1, 6, 30 }, // Item::diamond (treasure)
    { 265, -1, 6, 30 }, // Item::ironIngot (treasure)
    { 266, -1, 6, 30 }, // Item::goldIngot (treasure)
    { 267, -1, 1, 1 }, // Item::sword_iron (sword)
    { 268, -1, 1, 1 }, // Item::sword_wood (sword)
    { 269, -1, 1, 2 }, // Item::shovel_wood (shovel)
    { 270, -1, 1, 3 }, // Item::pickAxe_wood (pickaxe)
    { 271, -1, 1, 4 }, // Item::hatchet_wood (hatchet)
    { 272, -1, 1, 1 }, // Item::sword_stone (sword)
    { 273, -1, 1, 2 }, // Item::shovel_stone (shovel)
    { 274, -1, 1, 3 }, // Item::pickAxe_stone (pickaxe)
    { 275, -1, 1, 4 }, // Item::hatchet_stone (hatchet)
    { 276, -1, 1, 1 }, // Item::sword_diamond (sword)
    { 277, -1, 1, 2 }, // Item::shovel_diamond (shovel)
    { 278, -1, 1, 3 }, // Item::pickAxe_diamond (pickaxe)
    { 279, -1, 1, 4 }, // Item::hatchet_diamond (hatchet)
    { 280, -1, 0, 0 }, // Item::stick
    { 281, -1, 1, 25 }, // Item::bowl (utensil)
    { 282, -1, 2, 0 }, // Item::mushroomStew
    { 283, -1, 1, 1 }, // Item::sword_gold (sword)
    { 284, -1, 1, 2 }, // Item::shovel_gold (shovel)
    { 285, -1, 1, 3 }, // Item::pickAxe_gold (pickaxe)
    { 286, -1, 1, 4 }, // Item::hatchet_gold (hatchet)
    { 290, -1, 1, 5 }, // Item::hoe_wood (hoe)
    { 291, -1, 1, 5 }, // Item::hoe_stone (hoe)
    { 292, -1, 1, 5 }, // Item::hoe_iron (hoe)
    { 293, -1, 1, 5 }, // Item::hoe_diamond (hoe)
    { 294, -1, 1, 5 }, // Item::hoe_gold (hoe)
    { 297, -1, 2, 0 }, // Item::bread
    { 298, -1, 3, 7 }, // Item::helmet_cloth (helmet)
    { 299, -1, 3, 8 }, // Item::chestplate_cloth (chestplate)
    { 300, -1, 3, 9 }, // Item::leggings_cloth (leggings)
    { 301, -1, 3, 10 }, // Item::boots_cloth (boots)
    { 306, -1, 3, 7 }, // Item::helmet_iron (helmet)
    { 307, -1, 3, 8 }, // Item::chestplate_iron (chestplate)
    { 308, -1, 3, 9 }, // Item::leggings_iron (leggings)
    { 309, -1, 3, 10 }, // Item::boots_iron (boots)
    { 310, -1, 3, 7 }, // Item::helmet_diamond (helmet)
    { 311, -1, 3, 8 }, // Item::chestplate_diamond (chestplate)
    { 312, -1, 3, 9 }, // Item::leggings_diamond (leggings)
    { 313, -1, 3, 10 }, // Item::boots_diamond (boots)
    { 314, -1, 3, 7 }, // Item::helmet_gold (helmet)
    { 315, -1, 3, 8 }, // Item::chestplate_gold (chestplate)
    { 316, -1, 3, 9 }, // Item::leggings_gold (leggings)
    { 317, -1, 3, 10 }, // Item::boots_gold (boots)
    { 321, -1, 6, 32 }, // Item::painting (HangingItem)
    { 322, 0, 2, 0 }, // Item::apple_gold
    { 322, 1, 2, 0 }, // Item::apple_gold
    { 323, -1, 6, 32 }, // Item::sign (HangingItem)
    { 324, -1, 0, 6 }, // Item::door_wood (door)
    { 325, -1, 1, 25 }, // Item::bucket_empty (utensil)
    { 328, -1, 5, 0 }, // Item::minecart
    { 330, -1, 0, 6 }, // Item::door_iron (door)
    { 333, -1, 5, 0 }, // Item::boat
    { 339, -1, 6, 0 }, // Item::paper
    { 340, -1, 6, 0 }, // Item::book
    { 342, -1, 5, 0 }, // Item::minecart_chest
    { 343, -1, 5, 0 }, // Item::minecart_furnace
    { 345, -1, 1, 24 }, // Item::compass (pockettool)
    { 346, -1, 1, 35 }, // Item::fishingRod (rod)
    { 347, -1, 1, 24 }, // Item::clock (pockettool)
    { 351, -1, 6, 17 }, // Item::dye_powder (dyepowder)
    { 351, 4, 6, 17 }, // Item::dye_powder (dyepowder)
    { 353, -1, 2, 0 }, // Item::sugar
    { 354, -1, 2, 0 }, // Item::cake
    { 355, -1, 0, 0 }, // Item::bed
    { 356, -1, 4, 0 }, // Item::diode
    { 357, -1, 2, 0 }, // Item::cookie
    { 358, -1, 1, 24 }, // Item::map (pockettool)
    { 359, -1, 1, 27 }, // Item::shears (devicetool)
    { 361, -1, 2, 31 }, // Item::seeds_pumpkin (seed)
    { 362, -1, 2, 31 }, // Item::seeds_melon (seed)
    { 371, -1, 6, 30 }, // Item::goldNugget (treasure)
    { 374, -1, 1, 25 }, // Item::glassBottle (utensil)
    { 376, -1, 2, 0 }, // Item::fermentedSpiderEye
    { 377, -1, 2, 0 }, // Item::blazePowder
    { 378, -1, 2, 0 }, // Item::magmaCream
    { 379, -1, 0, 29 }, // Item::brewingStand (device)
    { 380, -1, 1, 25 }, // Item::cauldron (utensil)
    { 381, -1, 1, 24 }, // Item::eyeOfEnder (pockettool)
    { 382, -1, 2, 36 }, // Item::speckledMelon (giltFruit)
    { 385, -1, 1, 22 }, // Item::fireball (torch)
    { 388, -1, 6, 30 }, // Item::emerald (treasure)
    { 389, -1, 6, 32 }, // Item::frame (HangingItem)
    { 390, -1, 6, 0 }, // Item::flowerPot
    { 396, 0, 2, 36 }, // Item::carrotGolden (giltFruit)
    { 398, -1, 1, 35 }, // Item::carrotOnAStick (rod)
    { 400, -1, 2, 0 }, // Item::pumpkinPie
};
