; Generated by gen_imports.ps1 - do not edit.
.686
.model flat
option casemap:none
EXTERN _AcquireSRWLockExclusive@4:PROC
EXTERN _CloseThreadpoolTimer@4:PROC
EXTERN _CloseThreadpoolWait@4:PROC
EXTERN _CompareStringEx@36:PROC
EXTERN _CompareStringW@24:PROC
EXTERN _CreateEventExW@16:PROC
EXTERN _CreateFileW@28:PROC
EXTERN _CreateSemaphoreExW@24:PROC
EXTERN _CreateSymbolicLinkW@12:PROC
EXTERN _CreateThreadpoolTimer@12:PROC
EXTERN _CreateThreadpoolWait@12:PROC
EXTERN _DecodePointer@4:PROC
EXTERN _DeleteCriticalSection@4:PROC
EXTERN _EncodePointer@4:PROC
EXTERN _EnterCriticalSection@4:PROC
EXTERN _EnumSystemLocalesW@8:PROC
EXTERN _ExitProcess@4:PROC
EXTERN _FindClose@4:PROC
EXTERN _FindFirstFileExW@24:PROC
EXTERN _FindNextFileW@8:PROC
EXTERN _FlsAlloc@4:PROC
EXTERN _FlsFree@4:PROC
EXTERN _FlsGetValue@4:PROC
EXTERN _FlsSetValue@8:PROC
EXTERN _FlushProcessWriteBuffers@0:PROC
EXTERN _FormatMessageA@28:PROC
EXTERN _FreeEnvironmentStringsW@4:PROC
EXTERN _FreeLibrary@4:PROC
EXTERN _FreeLibraryAndExitThread@8:PROC
EXTERN _FreeLibraryWhenCallbackReturns@8:PROC
EXTERN _GetACP@0:PROC
EXTERN _GetCommandLineA@0:PROC
EXTERN _GetCommandLineW@0:PROC
EXTERN _GetConsoleMode@8:PROC
EXTERN _GetConsoleOutputCP@0:PROC
EXTERN _GetCPInfo@8:PROC
EXTERN _GetCurrentProcess@0:PROC
EXTERN _GetCurrentProcessId@0:PROC
EXTERN _GetCurrentProcessorNumber@0:PROC
EXTERN _GetCurrentThread@0:PROC
EXTERN _GetCurrentThreadId@0:PROC
EXTERN _GetDateFormatW@24:PROC
EXTERN _GetEnvironmentStringsW@0:PROC
EXTERN _GetFileInformationByHandleEx@16:PROC
EXTERN _GetFileType@4:PROC
EXTERN _GetLocaleInfoEx@16:PROC
EXTERN _GetLocaleInfoW@16:PROC
EXTERN _GetModuleFileNameW@12:PROC
EXTERN _GetModuleHandleExW@12:PROC
EXTERN _GetModuleHandleW@4:PROC
EXTERN _GetNativeSystemInfo@4:PROC
EXTERN _GetOEMCP@0:PROC
EXTERN _GetProcAddress@8:PROC
EXTERN _GetStartupInfoW@4:PROC
EXTERN _GetStdHandle@4:PROC
EXTERN _GetStringTypeW@16:PROC
EXTERN _GetSystemTimeAsFileTime@4:PROC
EXTERN _GetTempPathW@8:PROC
EXTERN _GetTickCount64@0:PROC
EXTERN _GetTimeFormatW@24:PROC
EXTERN _GetUserDefaultLCID@0:PROC
EXTERN _HeapAlloc@12:PROC
EXTERN _HeapReAlloc@16:PROC
EXTERN _HeapSize@12:PROC
EXTERN _InitializeCriticalSectionAndSpinCount@8:PROC
EXTERN _InitializeCriticalSectionEx@12:PROC
EXTERN _InitializeSListHead@4:PROC
EXTERN _InitOnceExecuteOnce@16:PROC
EXTERN _InterlockedFlushSList@4:PROC
EXTERN _InterlockedPushEntrySList@8:PROC
EXTERN _IsDebuggerPresent@0:PROC
EXTERN _IsProcessorFeaturePresent@4:PROC
EXTERN _IsThreadAFiber@0:PROC
EXTERN _IsValidCodePage@4:PROC
EXTERN _IsValidLocale@8:PROC
EXTERN _LCMapStringEx@36:PROC
EXTERN _LCMapStringW@24:PROC
EXTERN _LeaveCriticalSection@4:PROC
EXTERN _LoadLibraryExW@12:PROC
EXTERN _MultiByteToWideChar@24:PROC
EXTERN _OutputDebugStringW@4:PROC
EXTERN _RaiseException@16:PROC
EXTERN _ReadConsoleW@20:PROC
EXTERN _ReleaseSRWLockExclusive@4:PROC
EXTERN _SetConsoleCtrlHandler@8:PROC
EXTERN _SetEnvironmentVariableW@8:PROC
EXTERN _SetFileInformationByHandle@16:PROC
EXTERN _SetStdHandle@8:PROC
EXTERN _SetThreadpoolTimer@16:PROC
EXTERN _SetThreadpoolWait@12:PROC
EXTERN _SetUnhandledExceptionFilter@4:PROC
EXTERN _SleepConditionVariableSRW@16:PROC
EXTERN _TerminateProcess@8:PROC
EXTERN _TlsAlloc@0:PROC
EXTERN _TlsFree@4:PROC
EXTERN _TlsGetValue@4:PROC
EXTERN _TlsSetValue@8:PROC
EXTERN _TryAcquireSRWLockExclusive@4:PROC
EXTERN _UnhandledExceptionFilter@4:PROC
EXTERN _VirtualProtect@16:PROC
EXTERN _VirtualQuery@12:PROC
EXTERN _WaitForThreadpoolTimerCallbacks@8:PROC
EXTERN _WakeAllConditionVariable@4:PROC
EXTERN _WakeConditionVariable@4:PROC
EXTERN _WideCharToMultiByte@32:PROC
EXTERN _WriteConsoleW@20:PROC
.data
PUBLIC __imp__AcquireSRWLockExclusive@4
__imp__AcquireSRWLockExclusive@4 DD _AcquireSRWLockExclusive@4
PUBLIC __imp__CloseThreadpoolTimer@4
__imp__CloseThreadpoolTimer@4 DD _CloseThreadpoolTimer@4
PUBLIC __imp__CloseThreadpoolWait@4
__imp__CloseThreadpoolWait@4 DD _CloseThreadpoolWait@4
PUBLIC __imp__CompareStringEx@36
__imp__CompareStringEx@36 DD _CompareStringEx@36
PUBLIC __imp__CompareStringW@24
__imp__CompareStringW@24 DD _CompareStringW@24
PUBLIC __imp__CreateEventExW@16
__imp__CreateEventExW@16 DD _CreateEventExW@16
PUBLIC __imp__CreateFileW@28
__imp__CreateFileW@28 DD _CreateFileW@28
PUBLIC __imp__CreateSemaphoreExW@24
__imp__CreateSemaphoreExW@24 DD _CreateSemaphoreExW@24
PUBLIC __imp__CreateSymbolicLinkW@12
__imp__CreateSymbolicLinkW@12 DD _CreateSymbolicLinkW@12
PUBLIC __imp__CreateThreadpoolTimer@12
__imp__CreateThreadpoolTimer@12 DD _CreateThreadpoolTimer@12
PUBLIC __imp__CreateThreadpoolWait@12
__imp__CreateThreadpoolWait@12 DD _CreateThreadpoolWait@12
PUBLIC __imp__DecodePointer@4
__imp__DecodePointer@4 DD _DecodePointer@4
PUBLIC __imp__DeleteCriticalSection@4
__imp__DeleteCriticalSection@4 DD _DeleteCriticalSection@4
PUBLIC __imp__EncodePointer@4
__imp__EncodePointer@4 DD _EncodePointer@4
PUBLIC __imp__EnterCriticalSection@4
__imp__EnterCriticalSection@4 DD _EnterCriticalSection@4
PUBLIC __imp__EnumSystemLocalesW@8
__imp__EnumSystemLocalesW@8 DD _EnumSystemLocalesW@8
PUBLIC __imp__ExitProcess@4
__imp__ExitProcess@4 DD _ExitProcess@4
PUBLIC __imp__FindClose@4
__imp__FindClose@4 DD _FindClose@4
PUBLIC __imp__FindFirstFileExW@24
__imp__FindFirstFileExW@24 DD _FindFirstFileExW@24
PUBLIC __imp__FindNextFileW@8
__imp__FindNextFileW@8 DD _FindNextFileW@8
PUBLIC __imp__FlsAlloc@4
__imp__FlsAlloc@4 DD _FlsAlloc@4
PUBLIC __imp__FlsFree@4
__imp__FlsFree@4 DD _FlsFree@4
PUBLIC __imp__FlsGetValue@4
__imp__FlsGetValue@4 DD _FlsGetValue@4
PUBLIC __imp__FlsSetValue@8
__imp__FlsSetValue@8 DD _FlsSetValue@8
PUBLIC __imp__FlushProcessWriteBuffers@0
__imp__FlushProcessWriteBuffers@0 DD _FlushProcessWriteBuffers@0
PUBLIC __imp__FormatMessageA@28
__imp__FormatMessageA@28 DD _FormatMessageA@28
PUBLIC __imp__FreeEnvironmentStringsW@4
__imp__FreeEnvironmentStringsW@4 DD _FreeEnvironmentStringsW@4
PUBLIC __imp__FreeLibrary@4
__imp__FreeLibrary@4 DD _FreeLibrary@4
PUBLIC __imp__FreeLibraryAndExitThread@8
__imp__FreeLibraryAndExitThread@8 DD _FreeLibraryAndExitThread@8
PUBLIC __imp__FreeLibraryWhenCallbackReturns@8
__imp__FreeLibraryWhenCallbackReturns@8 DD _FreeLibraryWhenCallbackReturns@8
PUBLIC __imp__GetACP@0
__imp__GetACP@0 DD _GetACP@0
PUBLIC __imp__GetCommandLineA@0
__imp__GetCommandLineA@0 DD _GetCommandLineA@0
PUBLIC __imp__GetCommandLineW@0
__imp__GetCommandLineW@0 DD _GetCommandLineW@0
PUBLIC __imp__GetConsoleMode@8
__imp__GetConsoleMode@8 DD _GetConsoleMode@8
PUBLIC __imp__GetConsoleOutputCP@0
__imp__GetConsoleOutputCP@0 DD _GetConsoleOutputCP@0
PUBLIC __imp__GetCPInfo@8
__imp__GetCPInfo@8 DD _GetCPInfo@8
PUBLIC __imp__GetCurrentProcess@0
__imp__GetCurrentProcess@0 DD _GetCurrentProcess@0
PUBLIC __imp__GetCurrentProcessId@0
__imp__GetCurrentProcessId@0 DD _GetCurrentProcessId@0
PUBLIC __imp__GetCurrentProcessorNumber@0
__imp__GetCurrentProcessorNumber@0 DD _GetCurrentProcessorNumber@0
PUBLIC __imp__GetCurrentThread@0
__imp__GetCurrentThread@0 DD _GetCurrentThread@0
PUBLIC __imp__GetCurrentThreadId@0
__imp__GetCurrentThreadId@0 DD _GetCurrentThreadId@0
PUBLIC __imp__GetDateFormatW@24
__imp__GetDateFormatW@24 DD _GetDateFormatW@24
PUBLIC __imp__GetEnvironmentStringsW@0
__imp__GetEnvironmentStringsW@0 DD _GetEnvironmentStringsW@0
PUBLIC __imp__GetFileInformationByHandleEx@16
__imp__GetFileInformationByHandleEx@16 DD _GetFileInformationByHandleEx@16
PUBLIC __imp__GetFileType@4
__imp__GetFileType@4 DD _GetFileType@4
PUBLIC __imp__GetLocaleInfoEx@16
__imp__GetLocaleInfoEx@16 DD _GetLocaleInfoEx@16
PUBLIC __imp__GetLocaleInfoW@16
__imp__GetLocaleInfoW@16 DD _GetLocaleInfoW@16
PUBLIC __imp__GetModuleFileNameW@12
__imp__GetModuleFileNameW@12 DD _GetModuleFileNameW@12
PUBLIC __imp__GetModuleHandleExW@12
__imp__GetModuleHandleExW@12 DD _GetModuleHandleExW@12
PUBLIC __imp__GetModuleHandleW@4
__imp__GetModuleHandleW@4 DD _GetModuleHandleW@4
PUBLIC __imp__GetNativeSystemInfo@4
__imp__GetNativeSystemInfo@4 DD _GetNativeSystemInfo@4
PUBLIC __imp__GetOEMCP@0
__imp__GetOEMCP@0 DD _GetOEMCP@0
PUBLIC __imp__GetProcAddress@8
__imp__GetProcAddress@8 DD _GetProcAddress@8
PUBLIC __imp__GetStartupInfoW@4
__imp__GetStartupInfoW@4 DD _GetStartupInfoW@4
PUBLIC __imp__GetStdHandle@4
__imp__GetStdHandle@4 DD _GetStdHandle@4
PUBLIC __imp__GetStringTypeW@16
__imp__GetStringTypeW@16 DD _GetStringTypeW@16
PUBLIC __imp__GetSystemTimeAsFileTime@4
__imp__GetSystemTimeAsFileTime@4 DD _GetSystemTimeAsFileTime@4
PUBLIC __imp__GetTempPathW@8
__imp__GetTempPathW@8 DD _GetTempPathW@8
PUBLIC __imp__GetTickCount64@0
__imp__GetTickCount64@0 DD _GetTickCount64@0
PUBLIC __imp__GetTimeFormatW@24
__imp__GetTimeFormatW@24 DD _GetTimeFormatW@24
PUBLIC __imp__GetUserDefaultLCID@0
__imp__GetUserDefaultLCID@0 DD _GetUserDefaultLCID@0
PUBLIC __imp__HeapAlloc@12
__imp__HeapAlloc@12 DD _HeapAlloc@12
PUBLIC __imp__HeapReAlloc@16
__imp__HeapReAlloc@16 DD _HeapReAlloc@16
PUBLIC __imp__HeapSize@12
__imp__HeapSize@12 DD _HeapSize@12
PUBLIC __imp__InitializeCriticalSectionAndSpinCount@8
__imp__InitializeCriticalSectionAndSpinCount@8 DD _InitializeCriticalSectionAndSpinCount@8
PUBLIC __imp__InitializeCriticalSectionEx@12
__imp__InitializeCriticalSectionEx@12 DD _InitializeCriticalSectionEx@12
PUBLIC __imp__InitializeSListHead@4
__imp__InitializeSListHead@4 DD _InitializeSListHead@4
PUBLIC __imp__InitOnceExecuteOnce@16
__imp__InitOnceExecuteOnce@16 DD _InitOnceExecuteOnce@16
PUBLIC __imp__InterlockedFlushSList@4
__imp__InterlockedFlushSList@4 DD _InterlockedFlushSList@4
PUBLIC __imp__InterlockedPushEntrySList@8
__imp__InterlockedPushEntrySList@8 DD _InterlockedPushEntrySList@8
PUBLIC __imp__IsDebuggerPresent@0
__imp__IsDebuggerPresent@0 DD _IsDebuggerPresent@0
PUBLIC __imp__IsProcessorFeaturePresent@4
__imp__IsProcessorFeaturePresent@4 DD _IsProcessorFeaturePresent@4
PUBLIC __imp__IsThreadAFiber@0
__imp__IsThreadAFiber@0 DD _IsThreadAFiber@0
PUBLIC __imp__IsValidCodePage@4
__imp__IsValidCodePage@4 DD _IsValidCodePage@4
PUBLIC __imp__IsValidLocale@8
__imp__IsValidLocale@8 DD _IsValidLocale@8
PUBLIC __imp__LCMapStringEx@36
__imp__LCMapStringEx@36 DD _LCMapStringEx@36
PUBLIC __imp__LCMapStringW@24
__imp__LCMapStringW@24 DD _LCMapStringW@24
PUBLIC __imp__LeaveCriticalSection@4
__imp__LeaveCriticalSection@4 DD _LeaveCriticalSection@4
PUBLIC __imp__LoadLibraryExW@12
__imp__LoadLibraryExW@12 DD _LoadLibraryExW@12
PUBLIC __imp__MultiByteToWideChar@24
__imp__MultiByteToWideChar@24 DD _MultiByteToWideChar@24
PUBLIC __imp__OutputDebugStringW@4
__imp__OutputDebugStringW@4 DD _OutputDebugStringW@4
PUBLIC __imp__RaiseException@16
__imp__RaiseException@16 DD _RaiseException@16
PUBLIC __imp__ReadConsoleW@20
__imp__ReadConsoleW@20 DD _ReadConsoleW@20
PUBLIC __imp__ReleaseSRWLockExclusive@4
__imp__ReleaseSRWLockExclusive@4 DD _ReleaseSRWLockExclusive@4
PUBLIC __imp__SetConsoleCtrlHandler@8
__imp__SetConsoleCtrlHandler@8 DD _SetConsoleCtrlHandler@8
PUBLIC __imp__SetEnvironmentVariableW@8
__imp__SetEnvironmentVariableW@8 DD _SetEnvironmentVariableW@8
PUBLIC __imp__SetFileInformationByHandle@16
__imp__SetFileInformationByHandle@16 DD _SetFileInformationByHandle@16
PUBLIC __imp__SetStdHandle@8
__imp__SetStdHandle@8 DD _SetStdHandle@8
PUBLIC __imp__SetThreadpoolTimer@16
__imp__SetThreadpoolTimer@16 DD _SetThreadpoolTimer@16
PUBLIC __imp__SetThreadpoolWait@12
__imp__SetThreadpoolWait@12 DD _SetThreadpoolWait@12
PUBLIC __imp__SetUnhandledExceptionFilter@4
__imp__SetUnhandledExceptionFilter@4 DD _SetUnhandledExceptionFilter@4
PUBLIC __imp__SleepConditionVariableSRW@16
__imp__SleepConditionVariableSRW@16 DD _SleepConditionVariableSRW@16
PUBLIC __imp__TerminateProcess@8
__imp__TerminateProcess@8 DD _TerminateProcess@8
PUBLIC __imp__TlsAlloc@0
__imp__TlsAlloc@0 DD _TlsAlloc@0
PUBLIC __imp__TlsFree@4
__imp__TlsFree@4 DD _TlsFree@4
PUBLIC __imp__TlsGetValue@4
__imp__TlsGetValue@4 DD _TlsGetValue@4
PUBLIC __imp__TlsSetValue@8
__imp__TlsSetValue@8 DD _TlsSetValue@8
PUBLIC __imp__TryAcquireSRWLockExclusive@4
__imp__TryAcquireSRWLockExclusive@4 DD _TryAcquireSRWLockExclusive@4
PUBLIC __imp__UnhandledExceptionFilter@4
__imp__UnhandledExceptionFilter@4 DD _UnhandledExceptionFilter@4
PUBLIC __imp__VirtualProtect@16
__imp__VirtualProtect@16 DD _VirtualProtect@16
PUBLIC __imp__VirtualQuery@12
__imp__VirtualQuery@12 DD _VirtualQuery@12
PUBLIC __imp__WaitForThreadpoolTimerCallbacks@8
__imp__WaitForThreadpoolTimerCallbacks@8 DD _WaitForThreadpoolTimerCallbacks@8
PUBLIC __imp__WakeAllConditionVariable@4
__imp__WakeAllConditionVariable@4 DD _WakeAllConditionVariable@4
PUBLIC __imp__WakeConditionVariable@4
__imp__WakeConditionVariable@4 DD _WakeConditionVariable@4
PUBLIC __imp__WideCharToMultiByte@32
__imp__WideCharToMultiByte@32 DD _WideCharToMultiByte@32
PUBLIC __imp__WriteConsoleW@20
__imp__WriteConsoleW@20 DD _WriteConsoleW@20
END
