#pragma once

#include "pc/tuning/PcLegacyTuning.h"

// -----------------------------------------------------------------------------
// Generic low-console tuning aliases
// -----------------------------------------------------------------------------
// The game code should prefer these PLATFORM_* names for world/simulation/render
// budgets.  PS2-specific files may still use PS2_* directly.

#if PLATFORM_PS2
#  define PLATFORM_DEFAULT_RENDER_DISTANCE              PS2_DEFAULT_RENDER_DISTANCE
// ofMipmapLevel the performance profile starts from. See PS2_TERRAIN_MIPMAPS.
#  define PLATFORM_DEFAULT_MIPMAP_LEVEL                 (PS2_TERRAIN_MIPMAPS ? PS2_TERRAIN_MIP_LEVELS : 0)
#  define PLATFORM_VISIBLE_CHUNK_RADIUS                 PS2_VISIBLE_CHUNK_RADIUS
#  define PLATFORM_VISIBLE_CHUNK_DIAMETER               PS2_VISIBLE_CHUNK_DIAMETER
#  define PLATFORM_VERTICAL_CHUNK_COUNT                 PS2_VERTICAL_CHUNK_COUNT
#  define PLATFORM_CENTER_VERTICAL_RENDERERS            PS2_CENTER_VERTICAL_RENDERERS
#  define PLATFORM_CHUNK_CACHE_RADIUS                   PS2_CHUNK_CACHE_RADIUS
#  define PLATFORM_CHUNK_UNLOAD_RADIUS                  PS2_CHUNK_UNLOAD_RADIUS
#  define PLATFORM_CHUNK_MAP_RESERVE                    PS2_CHUNK_MAP_RESERVE
#  define PLATFORM_MAX_CHUNK_UNLOADS_PER_TICK           PS2_MAX_CHUNK_UNLOADS_PER_TICK
#  define PLATFORM_EMERGENCY_CHUNK_UNLOADS_PER_TICK     PS2_EMERGENCY_CHUNK_UNLOADS_PER_TICK
#  define PLATFORM_MIN_UNUSED_TICKS_BEFORE_UNLOAD       PS2_MIN_UNUSED_TICKS_BEFORE_UNLOAD
#  define PLATFORM_READ_ONLY_CHUNK_CACHE_RADIUS          PS2_READ_ONLY_CHUNK_CACHE_RADIUS
#  define PLATFORM_READ_ONLY_CHUNK_UNLOAD_RADIUS         PS2_READ_ONLY_CHUNK_UNLOAD_RADIUS
#  define PLATFORM_READ_ONLY_MAX_CHUNK_UNLOADS_PER_TICK PS2_READ_ONLY_MAX_CHUNK_UNLOADS_PER_TICK
#  define PLATFORM_READ_ONLY_MIN_UNUSED_TICKS_BEFORE_UNLOAD PS2_READ_ONLY_MIN_UNUSED_TICKS_BEFORE_UNLOAD
#  define PLATFORM_PRELOAD_RADIUS_BLOCKS                PS2_PRELOAD_RADIUS_BLOCKS
#  define PLATFORM_PLAYER_UPDATE_CHUNK_RANGE_BLOCKS     PS2_PLAYER_UPDATE_CHUNK_RANGE_BLOCKS
#  define PLATFORM_DISABLE_RUNTIME_AUTOSAVE             PS2_DISABLE_RUNTIME_AUTOSAVE
#  define PLATFORM_RUNTIME_AUTOSAVE_LEVEL_DATA          0
#  define PLATFORM_SKIP_NEW_WORLD_FULL_SAVE             PS2_SKIP_NEW_WORLD_FULL_SAVE
// Irrelevant on PS2 -- runtime autosave is off entirely there -- but the field
// still has to be initialised to something, so it takes the vanilla value.
#  define PLATFORM_AUTOSAVE_PERIOD_TICKS                40
// Runtime incremental saves stay small on PS2 to avoid long synchronous I/O stalls.
#  define PLATFORM_INCREMENTAL_CHUNK_SAVE_LIMIT         2
#  define PLATFORM_MESH_BUDGET                          1
#  define PLATFORM_MIN_RENDERER_UPDATES_PER_FRAME       PS2_MIN_RENDERER_UPDATES_PER_FRAME
#  define PLATFORM_MESH_WAIT_FOR_PENDING_SOURCES        PS2_MESH_WAIT_FOR_PENDING_SOURCES
#  define PLATFORM_MAX_RENDERER_UPDATES_PER_FRAME       PS2_MAX_RENDERER_UPDATES_PER_FRAME
#  define PLATFORM_COALESCE_MESH_REBUILDS               PS2_COALESCE_MESH_REBUILDS
#  define PLATFORM_URGENT_MESH_DISTANCE_SQ              PS2_URGENT_MESH_DISTANCE_SQ
#  define PLATFORM_URGENT_MESH_BUDGET_MS                PS2_URGENT_MESH_BUDGET_MS
#  define PLATFORM_URGENT_MESH_STEP_CAP                 PS2_URGENT_MESH_STEP_CAP
#  define PLATFORM_MESH_STAGING_SLOTS                   PS2_MESH_STAGING_SLOTS
#  define PLATFORM_MESH_STAGING_RESERVE_FOR_URGENT      PS2_MESH_STAGING_RESERVE_FOR_URGENT
#  define PLATFORM_DEFER_MESH_DURING_POPULATE           PS2_DEFER_MESH_DURING_POPULATE
#  define PLATFORM_POPULATE_MESH_DEFER_DISTANCE_SQ      PS2_POPULATE_MESH_DEFER_DISTANCE_SQ
#  define PLATFORM_MAX_RENDERED_SECTIONS_PER_PASS       PS2_MAX_RENDERED_SECTIONS_PER_PASS
#  define PLATFORM_CHUNK_BUILD_BLOCKS_PER_STEP          PS2_CHUNK_BUILD_BLOCKS_PER_STEP
#  define PLATFORM_RENDERER_UPDATE_CANDIDATES_PER_FRAME PS2_RENDERER_UPDATE_CANDIDATES_PER_FRAME
#  define PLATFORM_CULL_MISSING_CHUNK_BOUNDARY_FACES     PS2_CULL_MISSING_CHUNK_BOUNDARY_FACES
#  define PLATFORM_SKIP_ENCLOSED_OPAQUE_CUBES            PS2_SKIP_ENCLOSED_OPAQUE_CUBES
#  define PLATFORM_FAST_SIMPLE_CUBE_RENDER                PS2_FAST_SIMPLE_CUBE_RENDER
#  define PLATFORM_CPU_SECTION_OCCLUSION                  PS2_CPU_SECTION_OCCLUSION
#  define PLATFORM_CHUNK_BUILD_BUDGET_MS                PS2_CHUNK_BUILD_BUDGET_MS
#  define PLATFORM_CHUNK_BUILD_STEP_US                  PS2_CHUNK_BUILD_STEP_US
#  define PLATFORM_CHUNK_BUILD_TIME_CHECK_BLOCKS        PS2_CHUNK_BUILD_TIME_CHECK_BLOCKS
#  define PLATFORM_MESH_FACE_SORT                       PS2_MESH_FACE_SORT
#  define PLATFORM_FACE_BUCKET_CULL                     PS2_FACE_BUCKET_CULL
#  define PLATFORM_FACE_CULL_EYE_MARGIN                 PS2_FACE_CULL_EYE_MARGIN
#  define PLATFORM_MESH_SORT_MAX_QUADS                  PS2_MESH_SORT_MAX_QUADS
#  define PLATFORM_ENABLE_CHUNK_PREFETCH                PS2_ENABLE_CHUNK_PREFETCH
#  define PLATFORM_PREFETCH_CHUNK_INTERVAL_FRAMES       PS2_PREFETCH_CHUNK_INTERVAL_FRAMES
#  define PLATFORM_PREFETCH_CHUNKS_PER_STEP             PS2_PREFETCH_CHUNKS_PER_STEP
#  define PLATFORM_SKIP_TRANSPARENT_WORLD_PASS          PS2_SKIP_TRANSPARENT_WORLD_PASS
#  define PLATFORM_ENABLE_GREEDY_MESH                   PS2_ENABLE_GREEDY_MESH
#  define PLATFORM_SKIP_ENTITY_SHADOWS                  PS2_SKIP_ENTITY_SHADOWS
#  define PLATFORM_SKIP_WORLD_ENTITIES                  PS2_SKIP_WORLD_ENTITIES
#  define PLATFORM_SKIP_WORLD_PARTICLES                 PS2_SKIP_WORLD_PARTICLES
#  define PLATFORM_FAST_PARTICLE_PHYSICS                PS2_FAST_PARTICLE_PHYSICS
#  define PLATFORM_PARTICLE_BRIGHTNESS_INTERVAL         PS2_PARTICLE_BRIGHTNESS_INTERVAL
#  define PLATFORM_BLOCK_DESTROY_PARTICLE_GRID          PS2_BLOCK_DESTROY_PARTICLE_GRID
#  define PLATFORM_MAX_PARTICLES_PER_LAYER              PS2_MAX_PARTICLES_PER_LAYER
#  define PLATFORM_RANDOM_DISPLAY_PROBES                PS2_RANDOM_DISPLAY_PROBES
#  define PLATFORM_SKIP_RAIN_SNOW                       PS2_SKIP_RAIN_SNOW
#  define PLATFORM_SKIP_CLOUDS                          PS2_SKIP_CLOUDS
#  define PLATFORM_SKIP_BLOCK_SELECTION_BOX             PS2_SKIP_BLOCK_SELECTION_BOX
#  define PLATFORM_ENABLE_BLOCK_RAYTRACE                PS2_ENABLE_BLOCK_RAYTRACE
#  define PLATFORM_ENABLE_BLOCK_BREAK_OVERLAY           PS2_ENABLE_BLOCK_BREAK_OVERLAY
#  define PLATFORM_SKIP_HAND_RENDER                     PS2_SKIP_HAND_RENDER
#  define PLATFORM_SKIP_CAMERA_FX                       PS2_SKIP_CAMERA_FX
#  define PLATFORM_SKIP_MOB_SPAWNING                    PS2_SKIP_MOB_SPAWNING
#  define PLATFORM_RANDOM_TICK_CHUNK_RADIUS             PS2_RANDOM_TICK_CHUNK_RADIUS
#  define PLATFORM_MOB_SPAWN_CHUNK_RADIUS               PS2_MOB_SPAWN_CHUNK_RADIUS
#  define PLATFORM_RANDOM_BLOCK_TICKS_PER_CHUNK         PS2_RANDOM_BLOCK_TICKS_PER_CHUNK
#  define PLATFORM_RANDOM_TICK_CHUNKS_PER_TICK          PS2_RANDOM_TICK_CHUNKS_PER_TICK
#  define PLATFORM_RANDOM_TICK_PROFILE_INTERVAL         PS2_RANDOM_TICK_PROFILE_INTERVAL
#  define PLATFORM_CACHE_RANDOM_TICK_CHUNKS             PS2_CACHE_RANDOM_TICK_CHUNKS
#  define PLATFORM_CACHE_SPAWN_CHUNKS                   PS2_CACHE_SPAWN_CHUNKS
#  define PLATFORM_CACHE_ENTITY_CHUNK_EXISTENCE        PS2_CACHE_ENTITY_CHUNK_EXISTENCE
#  define PLATFORM_CACHE_RANDOM_DISPLAY_CHUNKS         PS2_CACHE_RANDOM_DISPLAY_CHUNKS
#  define PLATFORM_REUSE_RANDOM_DISPLAY_RNG             PS2_REUSE_RANDOM_DISPLAY_RNG
#  define PLATFORM_MAX_LIVE_MOBS                        PS2_MAX_LIVE_MOBS
#  define PLATFORM_WORLDGEN_ANIMAL_GROUP_MAX            PS2_WORLDGEN_ANIMAL_GROUP_MAX
#  define PLATFORM_WORLDGEN_ANIMAL_LIVE_MAX             PS2_WORLDGEN_ANIMAL_LIVE_MAX
#  define PLATFORM_MOB_SPAWN_Y_BAND                     PS2_MOB_SPAWN_Y_BAND
#  define PLATFORM_ENTITY_AI_NEAR_RADIUS_BLOCKS          PS2_ENTITY_AI_NEAR_RADIUS_BLOCKS
#  define PLATFORM_ENTITY_AI_FAR_RADIUS_BLOCKS           PS2_ENTITY_AI_FAR_RADIUS_BLOCKS
#  define PLATFORM_ENTITY_AI_MID_TICK_DIVISOR            PS2_ENTITY_AI_MID_TICK_DIVISOR
#  define PLATFORM_ENTITY_AI_FAR_TICK_DIVISOR            PS2_ENTITY_AI_FAR_TICK_DIVISOR
#  define PLATFORM_LIMIT_ENTITY_RENDER_DISTANCE           1
#  define PLATFORM_ENTITY_RENDER_RADIUS_BLOCKS            PS2_ENTITY_RENDER_RADIUS_BLOCKS
#  define PLATFORM_SHEEP_WOOL_LOD_DISTANCE_SQ            PS2_SHEEP_WOOL_LOD_DISTANCE_SQ
#  define PLATFORM_LIMIT_ENTITY_PUSH_COLLISIONS           1
#  define PLATFORM_ENTITY_PUSH_COLLISION_RADIUS_BLOCKS   PS2_ENTITY_PUSH_COLLISION_RADIUS_BLOCKS
#  define PLATFORM_FAST_BLOCK_COLLISIONS                 PS2_FAST_BLOCK_COLLISIONS
#  define PLATFORM_EARLY_UNIT_CUBE_COLLISION_TEST        PS2_EARLY_UNIT_CUBE_COLLISION_TEST
#  define PLATFORM_EARLY_COLLISION_EXIT                  PS2_EARLY_COLLISION_EXIT
#  define PLATFORM_ENTITY_QUERY_CACHE                    PS2_ENTITY_QUERY_CACHE
#  define PLATFORM_FLOAT_ENTITY_AI_MATH                  PS2_FLOAT_ENTITY_AI_MATH
#  define PLATFORM_FLOAT_ENTITY_CORE_MATH                PS2_FLOAT_ENTITY_CORE_MATH
#  define PLATFORM_FLOAT_FLUID_FLOW                       PS2_FLOAT_FLUID_FLOW
#  define PLATFORM_FLUID_FLOW_SEARCH_DEPTH                PS2_FLUID_FLOW_SEARCH_DEPTH
#  define PLATFORM_FAST_BIOME_BLEND                       0
#  define PLATFORM_FLOAT_EXPLOSION_MATH                   PS2_FLOAT_EXPLOSION_MATH
#  define PLATFORM_FLOAT_VECTOR_MATH                     PS2_FLOAT_VECTOR_MATH
#  define PLATFORM_FLOAT_COLLISION_SWEEP                 PS2_FLOAT_COLLISION_SWEEP
#  define PLATFORM_FLOAT_ENTITY_DISTANCE                 PS2_FLOAT_ENTITY_DISTANCE
#  define PLATFORM_REUSE_PATHFINDER                     1
#  define PLATFORM_PATHFIND_BUDGET_PER_TICK             PS2_PATHFIND_BUDGET_PER_TICK
#  define PLATFORM_PATHFIND_MAX_NODES                   PS2_PATHFIND_MAX_NODES
#  define PLATFORM_PATH_SHORTCUT_TICK_DIVISOR           PS2_PATH_SHORTCUT_TICK_DIVISOR
#  define PLATFORM_MOB_SPAWN_INTERVAL_TICKS             PS2_MOB_SPAWN_INTERVAL_TICKS
#  define PLATFORM_END_MAX_ENDERMEN                     PS2_END_MAX_ENDERMEN
#  define PLATFORM_ENDERMAN_TELEPORT_PARTICLES          PS2_ENDERMAN_TELEPORT_PARTICLES
#  define PLATFORM_DRAGON_COLLISION_TICK_DIVISOR        PS2_DRAGON_COLLISION_TICK_DIVISOR
#  define PLATFORM_END_RESIDENT_CHUNK_RADIUS            PS2_END_RESIDENT_CHUNK_RADIUS
#  define PLATFORM_FORCE_FULLBRIGHT_TERRAIN             PS2_FORCE_FULLBRIGHT_TERRAIN
#  define PLATFORM_SEED_GAP_LIGHTING_ON_RELIGHT         PS2_SEED_GAP_LIGHTING_ON_RELIGHT
#  define PLATFORM_SKIP_CAVE_GENERATION                 PS2_SKIP_CAVE_GENERATION
#  define PLATFORM_CAVE_SOURCE_RADIUS                   PS2_CAVE_SOURCE_RADIUS
#  define PLATFORM_SKIP_RAVINE_GENERATION               PS2_SKIP_RAVINE_GENERATION
#  define PLATFORM_CAVE_RARITY                          PS2_CAVE_RARITY
#  define PLATFORM_FLOAT_CAVE_GENERATION                PS2_FLOAT_CAVE_GENERATION
#  define PLATFORM_GENERATE_MAP_FEATURES                PS2_GENERATE_MAP_FEATURES
#  define PLATFORM_USE_HEIGHTMAP_TERRAIN                PS2_USE_HEIGHTMAP_TERRAIN
#  define PLATFORM_FAST_SURFACE_PASS                    PS2_FAST_SURFACE_PASS
#  define PLATFORM_PRECOMPUTE_INITIAL_HEIGHTMAP          PS2_PRECOMPUTE_INITIAL_HEIGHTMAP
#  define PLATFORM_BATCH_INITIAL_SKYLIGHT_RENDER_UPDATES PS2_BATCH_INITIAL_SKYLIGHT_RENDER_UPDATES
#  define PLATFORM_BULK_GENERATED_CHUNK_IMPORT           PS2_BULK_GENERATED_CHUNK_IMPORT
#  define PLATFORM_BATCH_POPULATION_LIGHTING             PS2_BATCH_POPULATION_LIGHTING
#  define PLATFORM_POPULATION_BLOCK_WRITER                PS2_POPULATION_BLOCK_WRITER
#  define PLATFORM_HEIGHTMAP_SEA_LEVEL                  PS2_HEIGHTMAP_SEA_LEVEL
#  define PLATFORM_HEIGHTMAP_BASE_HEIGHT                PS2_HEIGHTMAP_BASE_HEIGHT
#  define PLATFORM_HEIGHTMAP_AMPLITUDE                  PS2_HEIGHTMAP_AMPLITUDE
#  define PLATFORM_HEIGHTMAP_FREEZE_TEMP                PS2_HEIGHTMAP_FREEZE_TEMP
#  define PLATFORM_POPULATE_WATER_SPRINGS              PS2_POPULATE_WATER_SPRINGS
#  define PLATFORM_POPULATE_LAVA_SPRINGS               PS2_POPULATE_LAVA_SPRINGS
#  define PLATFORM_POPULATE_DUNGEONS                   PS2_POPULATE_DUNGEONS
#  define PLATFORM_POPULATE_LAKES                      PS2_POPULATE_LAKES
#  define PLATFORM_POPULATE_WORLDGEN_ANIMALS           PS2_POPULATE_WORLDGEN_ANIMALS
#  define PLATFORM_FLOWER_PLACEMENT_ATTEMPTS           PS2_FLOWER_PLACEMENT_ATTEMPTS
#  define PLATFORM_TALL_GRASS_PLACEMENT_ATTEMPTS       PS2_TALL_GRASS_PLACEMENT_ATTEMPTS
#  define PLATFORM_POPULATE_TREE_BONUS                  PS2_POPULATE_TREE_BONUS
#  define PLATFORM_POPULATE_TREES_PER_CHUNK_MAX         PS2_POPULATE_TREES_PER_CHUNK_MAX
#  define PLATFORM_POPULATE_GRASS_PER_CHUNK_MAX         PS2_POPULATE_GRASS_PER_CHUNK_MAX
#  define PLATFORM_POPULATE_JUNGLE_HUGE_TREES           PS2_POPULATE_JUNGLE_HUGE_TREES
#  define PLATFORM_POPULATE_JUNGLE_VINES                PS2_POPULATE_JUNGLE_VINES
#  define PLATFORM_POPULATE_CLAY_VEINS                 PS2_POPULATE_CLAY_VEINS
#  define PLATFORM_POPULATE_DIRT_VEINS                 PS2_POPULATE_DIRT_VEINS
#  define PLATFORM_POPULATE_GRAVEL_VEINS               PS2_POPULATE_GRAVEL_VEINS
#  define PLATFORM_POPULATE_SNOW_PASS                  PS2_POPULATE_SNOW_PASS
#  define PLATFORM_DEFERRED_POPULATE                   1
#  define PLATFORM_INCREMENTAL_POPULATE                1
#  define PLATFORM_CHUNK_LOCAL_DECORATION              PS2_CHUNK_LOCAL_DECORATION
#  define PLATFORM_POPULATE_CHUNKS_PER_TICK            PS2_POPULATE_CHUNKS_PER_TICK
#  define PLATFORM_POPULATE_STEPS_PER_TICK             PS2_POPULATE_STEPS_PER_TICK
// Decoration budget for a tick that already published a column. 0 reproduces
// the original stand-down, because drainPendingPopulate() returns on a budget
// of 0; see the Wii override for why a non-zero value exists.
#  define PLATFORM_POPULATE_STEPS_AFTER_PUBLISH        0
#  define PLATFORM_POPULATE_BUDGET_US                  PS2_POPULATE_BUDGET_US
#  define PLATFORM_POPULATE_SNOW_COLUMNS_PER_STEP      16
#  define PLATFORM_GENERATE_SYNC_RADIUS                PS2_GENERATE_SYNC_RADIUS
#  define PLATFORM_GENERATE_CHUNKS_PER_TICK            PS2_GENERATE_CHUNKS_PER_TICK
#  define PLATFORM_INCREMENTAL_CHUNK_GENERATION        PS2_INCREMENTAL_CHUNK_GENERATION
#  define PLATFORM_GENERATION_STEPS_PER_TICK            PS2_GENERATION_STEPS_PER_TICK
#  define PLATFORM_GENERATION_BUDGET_US                 PS2_GENERATION_BUDGET_US
#  define PLATFORM_GENERATION_STEPS_PER_FRAME           PS2_GENERATION_STEPS_PER_FRAME
#  define PLATFORM_GENERATION_FRAME_BUDGET_US           PS2_GENERATION_FRAME_BUDGET_US
#  define PLATFORM_STREAMING_FRAME_BUDGET_US            PS2_STREAMING_FRAME_BUDGET_US
#  define PLATFORM_GENERATION_SOURCE_COLUMNS_PER_STEP   PS2_GENERATION_SOURCE_COLUMNS_PER_STEP
#  define PLATFORM_STRUCTURE_SOURCE_COLUMNS_PER_STEP    PS2_STRUCTURE_SOURCE_COLUMNS_PER_STEP
#  define PLATFORM_LIGHTING_UPDATES_PER_FRAME           PS2_LIGHTING_UPDATES_PER_FRAME
#  define PLATFORM_LIGHTING_INTERACTIVE_QUEUE_MAX       PS2_LIGHTING_INTERACTIVE_QUEUE_MAX
#  define PLATFORM_LIGHTING_INTERACTIVE_BURST           PS2_LIGHTING_INTERACTIVE_BURST
#  define PLATFORM_LIGHTING_BUDGET_US                   PS2_LIGHTING_BUDGET_US
#  define PLATFORM_LIGHTING_MERGE_SCAN                   PS2_LIGHTING_MERGE_SCAN
#  define PLATFORM_LIGHTING_QUEUE_HARD_CAP               PS2_LIGHTING_QUEUE_HARD_CAP
#  define PLATFORM_FAST_LIGHTING_CHUNK_ACCESS              PS2_FAST_LIGHTING_CHUNK_ACCESS
#  define PLATFORM_FLOAT_TERRAIN_NOISE                    1
#  define PLATFORM_FLOAT_BIOME_NOISE                   PS2_FLOAT_BIOME_NOISE
#  define PLATFORM_FAST_BIOME_SOURCE                   PS2_FAST_BIOME_SOURCE
#  define PLATFORM_FLOAT_ORE_VEINS                     PS2_FLOAT_ORE_VEINS
#  define PLATFORM_TERRAIN_DENSITY_OCTAVES              PS2_TERRAIN_DENSITY_OCTAVES
#  define PLATFORM_TERRAIN_SELECT_OCTAVES               PS2_TERRAIN_SELECT_OCTAVES
#  define PLATFORM_TERRAIN_DENSITY_SKIP_FINE_OCTAVES    0
#  define PLATFORM_TERRAIN_SELECT_SKIP_FINE_OCTAVES     0
#  define PLATFORM_STRUCTURE_START_RETENTION_BLOCKS     0
#  define PLATFORM_SIN_TABLE_BITS                      PS2_SIN_TABLE_BITS
#  define PLATFORM_INTEGER_FLOOR_DOUBLE               PS2_INTEGER_FLOOR_DOUBLE
#  define PLATFORM_LEGACY_GUI_SCALE                    PS2_LEGACY_GUI_SCALE
#  define PLATFORM_LEGACY_CREATE_WORLD_PANEL_WIDTH     PS2_LEGACY_CREATE_WORLD_PANEL_WIDTH
#  define PLATFORM_FORCE_GUI_SCALE                     PS2_FORCE_GUI_SCALE
#  define PLATFORM_NEAR_PLANE                          PS2_NEAR_PLANE
#  define PLATFORM_SHOW_LAGOMETER                      PS2_SHOW_LAGOMETER
#  define PLATFORM_RENDERER_AABB_MARGIN                PS2_RENDERER_AABB_MARGIN
#  define PLATFORM_CURSOR_TEXTURE                      PS2_CURSOR_TEXTURE
#  define PLATFORM_CURSOR_SIZE                         PS2_CURSOR_SIZE
#  define PLATFORM_DYNAMIC_TEXTURE_INTERVAL_TICKS      PS2_DYNAMIC_TEXTURE_INTERVAL_TICKS
#  define PLATFORM_TESSELLATOR_CONVERT_QUADS             PS2_TESSELLATOR_CONVERT_QUADS
#  define PLATFORM_TESSELLATOR_BUFFER_INTS               PS2_TESSELLATOR_BUFFER_INTS
#  define PLATFORM_FLOAT_VERTEX_MATH                     PS2_FLOAT_VERTEX_MATH
#  define PLATFORM_FAST_CHUNK_BLOCK_READS                PS2_FAST_CHUNK_BLOCK_READS
#  define PLATFORM_FAST_BLOCK_COUNT_SCAN                 1
#  define PLATFORM_MP_DEFERRED_CHUNKS                    PS2_MP_DEFERRED_CHUNKS
#  define PLATFORM_MP_COMPRESSED_CHUNK_CACHE_BYTES       PS2_MP_COMPRESSED_CHUNK_CACHE_BYTES
#  define PLATFORM_MP_CHUNK_PROMOTIONS_PER_TICK          PS2_MP_CHUNK_PROMOTIONS_PER_TICK
#  define PLATFORM_MP_MAX_DEFERRED_CHUNKS                PS2_MP_MAX_DEFERRED_CHUNKS
#  define PLATFORM_MP_MAX_CHANGES_PER_CHUNK              PS2_MP_MAX_CHANGES_PER_CHUNK
#  define PLATFORM_MP_MAX_DEFERRED_CHANGES               PS2_MP_MAX_DEFERRED_CHANGES
#else
#  define PLATFORM_DEFAULT_RENDER_DISTANCE              (PLATFORM_PC_LEGACY ? PC_LEGACY_DEFAULT_RENDER_DISTANCE : 0)
#  define PLATFORM_DEFAULT_MIPMAP_LEVEL                 0
#  define PLATFORM_VISIBLE_CHUNK_RADIUS                 (PLATFORM_PC_LEGACY ? PC_LEGACY_VISIBLE_CHUNK_RADIUS : 8)
#  define PLATFORM_VISIBLE_CHUNK_DIAMETER               (PLATFORM_VISIBLE_CHUNK_RADIUS * 2 + 1)
#  define PLATFORM_VERTICAL_CHUNK_COUNT                 (PLATFORM_PC_LEGACY ? PC_LEGACY_VERTICAL_CHUNK_COUNT : 8)
#  define PLATFORM_CENTER_VERTICAL_RENDERERS            (PLATFORM_PC_LEGACY ? PC_LEGACY_CENTER_VERTICAL_RENDERERS : 0)
#  define PLATFORM_CHUNK_CACHE_RADIUS                   (PLATFORM_PC_LEGACY ? PC_LEGACY_CHUNK_CACHE_RADIUS : 8)
#  define PLATFORM_CHUNK_UNLOAD_RADIUS                  (PLATFORM_PC_LEGACY ? PC_LEGACY_CHUNK_UNLOAD_RADIUS : 12)
#  define PLATFORM_CHUNK_MAP_RESERVE                    0
// Vanilla eviction rate: 4 chunks per tick, and only after 200 ticks (10 s)
// untouched. Unchanged from the values this table replaced.
#  define PLATFORM_MAX_CHUNK_UNLOADS_PER_TICK           4
#  define PLATFORM_EMERGENCY_CHUNK_UNLOADS_PER_TICK     16
#  define PLATFORM_MIN_UNUSED_TICKS_BEFORE_UNLOAD       200
#  define PLATFORM_READ_ONLY_CHUNK_CACHE_RADIUS          PLATFORM_CHUNK_CACHE_RADIUS
#  define PLATFORM_READ_ONLY_CHUNK_UNLOAD_RADIUS         PLATFORM_CHUNK_UNLOAD_RADIUS
#  define PLATFORM_READ_ONLY_MAX_CHUNK_UNLOADS_PER_TICK PLATFORM_MAX_CHUNK_UNLOADS_PER_TICK
#  define PLATFORM_READ_ONLY_MIN_UNUSED_TICKS_BEFORE_UNLOAD PLATFORM_MIN_UNUSED_TICKS_BEFORE_UNLOAD
#  define PLATFORM_PRELOAD_RADIUS_BLOCKS                (PLATFORM_PC_LEGACY ? PC_LEGACY_PRELOAD_RADIUS_BLOCKS : 128)
#  define PLATFORM_PLAYER_UPDATE_CHUNK_RANGE_BLOCKS     32
#  define PLATFORM_DISABLE_RUNTIME_AUTOSAVE             0
#  define PLATFORM_RUNTIME_AUTOSAVE_LEVEL_DATA          1
#  define PLATFORM_SKIP_NEW_WORLD_FULL_SAVE             0
// Vanilla Beta 1.7.3: World::autosavePeriod, in world ticks. 40 ticks is two
// seconds, and each firing rewrites level.dat and flushes up to two dirty chunks
// through the deflate path. Cheap against a desktop page cache; not cheap
// against a console filesystem, which is why it is a knob now.
#  define PLATFORM_AUTOSAVE_PERIOD_TICKS                40
// Release 1.2.5 saves at most 24 dirty chunks during an incremental save.
#  define PLATFORM_INCREMENTAL_CHUNK_SAVE_LIMIT         24
// Whether chunk meshing is bounded per frame. Off on the desktop, where
// EntityRenderer's own time-limited retry loop is the budget and there is plenty
// of headroom to overshoot it.
//
// Turning this ON does two things that have to happen together, or neither
// works: it bounds the work inside RenderGlobal::updateRenderers, and it stops
// EntityRenderer calling updateRenderers repeatedly within one frame. Bounding
// only the first is pointless -- the outer loop just calls it again until the
// same total work is done, one budget at a time.
#  define PLATFORM_MESH_BUDGET                          (PLATFORM_PC_LEGACY ? PC_LEGACY_MESH_BUDGET : 0)
#  define PLATFORM_MIN_RENDERER_UPDATES_PER_FRAME       (PLATFORM_PC_LEGACY ? PC_LEGACY_MIN_RENDERER_UPDATES_PER_FRAME : 1)
// Only the bounded console profile keeps a streaming ring wider than its render
// window, so nothing else can hit the wait described in Ps2MeshTuning.h.
#  define PLATFORM_MESH_WAIT_FOR_PENDING_SOURCES        1
#  define PLATFORM_MAX_RENDERER_UPDATES_PER_FRAME       (PLATFORM_PC_LEGACY ? PC_LEGACY_MAX_RENDERER_UPDATES_PER_FRAME : 99)
#  define PLATFORM_COALESCE_MESH_REBUILDS               (PLATFORM_PC_LEGACY ? PC_LEGACY_COALESCE_MESH_REBUILDS : 0)
// Edit-latency lane (console only; see RenderGlobal::updateRenderers). 0 off.
#  define PLATFORM_URGENT_MESH_DISTANCE_SQ              0.0f
#  define PLATFORM_URGENT_MESH_BUDGET_MS                0
#  define PLATFORM_URGENT_MESH_STEP_CAP                 64
#  define PLATFORM_MESH_STAGING_SLOTS                   0
#  define PLATFORM_MESH_STAGING_RESERVE_FOR_URGENT      0
#  define PLATFORM_DEFER_MESH_DURING_POPULATE           (PLATFORM_PC_LEGACY ? PC_LEGACY_DEFER_MESH_DURING_POPULATE : 0)
#  define PLATFORM_POPULATE_MESH_DEFER_DISTANCE_SQ      (PLATFORM_PC_LEGACY ? PC_LEGACY_POPULATE_MESH_DEFER_DISTANCE_SQ : 0.0f)
#  define PLATFORM_MAX_RENDERED_SECTIONS_PER_PASS       999999
#  define PLATFORM_CHUNK_BUILD_BLOCKS_PER_STEP          (PLATFORM_PC_LEGACY ? PC_LEGACY_CHUNK_BUILD_BLOCKS_PER_STEP : 4096)
#  define PLATFORM_RENDERER_UPDATE_CANDIDATES_PER_FRAME (PLATFORM_PC_LEGACY ? PC_LEGACY_RENDERER_UPDATE_CANDIDATES_PER_FRAME : 99)
#  define PLATFORM_SKIP_ENCLOSED_OPAQUE_CUBES            0
#  define PLATFORM_FAST_SIMPLE_CUBE_RENDER                0
#  define PLATFORM_CPU_SECTION_OCCLUSION                  0
#  define PLATFORM_CULL_MISSING_CHUNK_BOUNDARY_FACES     0
#  define PLATFORM_CHUNK_BUILD_BUDGET_MS                (PLATFORM_PC_LEGACY ? PC_LEGACY_CHUNK_BUILD_BUDGET_MS : 0)
#  define PLATFORM_CHUNK_BUILD_STEP_US                  (PLATFORM_PC_LEGACY ? PC_LEGACY_CHUNK_BUILD_STEP_US : 0)
#  define PLATFORM_CHUNK_BUILD_TIME_CHECK_BLOCKS        32
#  define PLATFORM_MESH_FACE_SORT                       0
#  define PLATFORM_FACE_BUCKET_CULL                     0
#  define PLATFORM_FACE_CULL_EYE_MARGIN                 0.0f
#  define PLATFORM_MESH_SORT_MAX_QUADS                  0
#  define PLATFORM_ENABLE_CHUNK_PREFETCH                (PLATFORM_PC_LEGACY ? PC_LEGACY_ENABLE_CHUNK_PREFETCH : 0)
#  define PLATFORM_PREFETCH_CHUNK_INTERVAL_FRAMES       (PLATFORM_PC_LEGACY ? PC_LEGACY_PREFETCH_CHUNK_INTERVAL_FRAMES : 20)
#  define PLATFORM_PREFETCH_CHUNKS_PER_STEP             (PLATFORM_PC_LEGACY ? PC_LEGACY_PREFETCH_CHUNKS_PER_STEP : 1)
#  define PLATFORM_SKIP_TRANSPARENT_WORLD_PASS          0
#  define PLATFORM_ENABLE_GREEDY_MESH                   0
#  define PLATFORM_SKIP_ENTITY_SHADOWS                  (PLATFORM_PC_LEGACY ? PC_LEGACY_SKIP_ENTITY_SHADOWS : 0)
#  define PLATFORM_SKIP_WORLD_ENTITIES                  0
#  define PLATFORM_SKIP_WORLD_PARTICLES                 (PLATFORM_PC_LEGACY ? PC_LEGACY_SKIP_WORLD_PARTICLES : 0)
// Vanilla particle behaviour: full entity physics, brightness per frame,
// 4x4x4 fragments per broken block, 4000 per layer, 1000 display probes.
#  define PLATFORM_FAST_PARTICLE_PHYSICS                0
#  define PLATFORM_PARTICLE_BRIGHTNESS_INTERVAL         1
#  define PLATFORM_BLOCK_DESTROY_PARTICLE_GRID          4
#  define PLATFORM_MAX_PARTICLES_PER_LAYER              4000
#  define PLATFORM_RANDOM_DISPLAY_PROBES                1000
#  define PLATFORM_SKIP_RAIN_SNOW                       (PLATFORM_PC_LEGACY ? PC_LEGACY_SKIP_RAIN_SNOW : 0)
#  define PLATFORM_SKIP_CLOUDS                          0
#  define PLATFORM_SKIP_BLOCK_SELECTION_BOX             0
#  define PLATFORM_ENABLE_BLOCK_RAYTRACE                1
#  define PLATFORM_ENABLE_BLOCK_BREAK_OVERLAY           1
#  define PLATFORM_SKIP_HAND_RENDER                     0
#  define PLATFORM_SKIP_CAMERA_FX                       (PLATFORM_PC_LEGACY ? PC_LEGACY_SKIP_CAMERA_FX : 0)
#  define PLATFORM_SKIP_MOB_SPAWNING                    0
#  define PLATFORM_RANDOM_TICK_CHUNK_RADIUS             (PLATFORM_PC_LEGACY ? PC_LEGACY_RANDOM_TICK_CHUNK_RADIUS : 7)
// Platforms whose streaming cache IS the simulation window keep the old coupling.
#  define PLATFORM_MOB_SPAWN_CHUNK_RADIUS               (PLATFORM_PC_LEGACY ? PC_LEGACY_MOB_SPAWN_CHUNK_RADIUS : 8)
#  define PLATFORM_RANDOM_BLOCK_TICKS_PER_CHUNK         (PLATFORM_PC_LEGACY ? PC_LEGACY_RANDOM_BLOCK_TICKS_PER_CHUNK : 0)
#  define PLATFORM_RANDOM_TICK_CHUNKS_PER_TICK          (PLATFORM_PC_LEGACY ? PC_LEGACY_RANDOM_TICK_CHUNKS_PER_TICK : 0)
#  define PLATFORM_RANDOM_TICK_PROFILE_INTERVAL         0
#  define PLATFORM_CACHE_RANDOM_TICK_CHUNKS             (PLATFORM_PC_LEGACY ? PC_LEGACY_CACHE_RANDOM_TICK_CHUNKS : 0)
#  define PLATFORM_CACHE_SPAWN_CHUNKS                   (PLATFORM_PC_LEGACY ? PC_LEGACY_CACHE_SPAWN_CHUNKS : 0)
#  define PLATFORM_CACHE_ENTITY_CHUNK_EXISTENCE        (PLATFORM_PC_LEGACY ? PC_LEGACY_CACHE_ENTITY_CHUNK_EXISTENCE : 0)
#  define PLATFORM_CACHE_RANDOM_DISPLAY_CHUNKS         (PLATFORM_PC_LEGACY ? PC_LEGACY_CACHE_RANDOM_DISPLAY_CHUNKS : 0)
#  define PLATFORM_REUSE_RANDOM_DISPLAY_RNG             (PLATFORM_PC_LEGACY ? PC_LEGACY_REUSE_RANDOM_DISPLAY_RNG : 0)
#  define PLATFORM_MAX_LIVE_MOBS                        (PLATFORM_PC_LEGACY ? PC_LEGACY_MAX_LIVE_MOBS : 0x7fffffff)
// Worldgen animal group bounds (console only, see the PS2 table). 0 = vanilla.
#  define PLATFORM_WORLDGEN_ANIMAL_GROUP_MAX            0
#  define PLATFORM_WORLDGEN_ANIMAL_LIVE_MAX             0
#  define PLATFORM_MOB_SPAWN_Y_BAND                     0
#  define PLATFORM_ENTITY_AI_NEAR_RADIUS_BLOCKS          (PLATFORM_PC_LEGACY ? PC_LEGACY_ENTITY_AI_NEAR_RADIUS_BLOCKS : 1.0e9f)
#  define PLATFORM_ENTITY_AI_FAR_RADIUS_BLOCKS           (PLATFORM_PC_LEGACY ? PC_LEGACY_ENTITY_AI_FAR_RADIUS_BLOCKS : 1.0e9f)
#  define PLATFORM_ENTITY_AI_MID_TICK_DIVISOR            (PLATFORM_PC_LEGACY ? PC_LEGACY_ENTITY_AI_MID_TICK_DIVISOR : 1)
#  define PLATFORM_ENTITY_AI_FAR_TICK_DIVISOR            (PLATFORM_PC_LEGACY ? PC_LEGACY_ENTITY_AI_FAR_TICK_DIVISOR : 1)
#  define PLATFORM_LIMIT_ENTITY_RENDER_DISTANCE           (PLATFORM_PC_LEGACY ? PC_LEGACY_LIMIT_ENTITY_RENDER_DISTANCE : 0)
#  define PLATFORM_ENTITY_RENDER_RADIUS_BLOCKS            (PLATFORM_PC_LEGACY ? PC_LEGACY_ENTITY_RENDER_RADIUS_BLOCKS : 1.0e9f)
// Sheep wool pass cut-off (console only, see the PS2 table). 0 off.
#  define PLATFORM_SHEEP_WOOL_LOD_DISTANCE_SQ            0.0f
#  define PLATFORM_LIMIT_ENTITY_PUSH_COLLISIONS           (PLATFORM_PC_LEGACY ? PC_LEGACY_LIMIT_ENTITY_PUSH_COLLISIONS : 0)
#  define PLATFORM_ENTITY_PUSH_COLLISION_RADIUS_BLOCKS   (PLATFORM_PC_LEGACY ? PC_LEGACY_ENTITY_PUSH_COLLISION_RADIUS_BLOCKS : 1.0e9f)
#  define PLATFORM_FAST_BLOCK_COLLISIONS                 (PLATFORM_PC_LEGACY ? PC_LEGACY_FAST_BLOCK_COLLISIONS : 0)
#  define PLATFORM_EARLY_UNIT_CUBE_COLLISION_TEST        (PLATFORM_PC_LEGACY ? PC_LEGACY_EARLY_UNIT_CUBE_COLLISION_TEST : 0)
#  define PLATFORM_EARLY_COLLISION_EXIT                  (PLATFORM_PC_LEGACY ? PC_LEGACY_EARLY_COLLISION_EXIT : 0)
#  define PLATFORM_ENTITY_QUERY_CACHE                    (PLATFORM_PC_LEGACY ? PC_LEGACY_ENTITY_QUERY_CACHE : 0)
#  define PLATFORM_FLOAT_ENTITY_AI_MATH                  (PLATFORM_PC_LEGACY ? PC_LEGACY_FLOAT_ENTITY_AI_MATH : 0)
#  define PLATFORM_FLOAT_ENTITY_CORE_MATH                (PLATFORM_PC_LEGACY ? PC_LEGACY_FLOAT_ENTITY_CORE_MATH : 0)
#  define PLATFORM_FLOAT_FLUID_FLOW                       (PLATFORM_PC_LEGACY ? PC_LEGACY_FLOAT_FLUID_FLOW : 0)
// How far BlockFlowing::calculateFlowCost looks for a drop to steer toward.
// Vanilla 4; the search fans out threefold per level.
#  define PLATFORM_FLUID_FLOW_SEARCH_DEPTH                4
#  define PLATFORM_FAST_BIOME_BLEND                       0
#  define PLATFORM_FLOAT_EXPLOSION_MATH                   (PLATFORM_PC_LEGACY ? PC_LEGACY_FLOAT_EXPLOSION_MATH : 0)
// Normal desktop keeps the exact double Vec3D helpers and block ray cast.
// Legacy PC reuses the low-CPU float vector path; the AABB sweep stays exact.
#  define PLATFORM_FLOAT_VECTOR_MATH                     (PLATFORM_PC_LEGACY ? PC_LEGACY_FLOAT_VECTOR_MATH : 0)
#  define PLATFORM_FLOAT_COLLISION_SWEEP                 0
#  define PLATFORM_FLOAT_ENTITY_DISTANCE                 0
#  define PLATFORM_REUSE_PATHFINDER                     (PLATFORM_BOUNDED_PATHFIND || (PLATFORM_PC_LEGACY ? PC_LEGACY_REUSE_PATHFINDER : 0))
#  define PLATFORM_PATHFIND_BUDGET_PER_TICK             (PLATFORM_PC_LEGACY ? PC_LEGACY_PATHFIND_BUDGET_PER_TICK : 0x7fffffff)
#  define PLATFORM_PATHFIND_MAX_NODES                   (PLATFORM_PC_LEGACY ? PC_LEGACY_PATHFIND_MAX_NODES : 0x7fffffff)
#  define PLATFORM_PATH_SHORTCUT_TICK_DIVISOR           (PLATFORM_PC_LEGACY ? PC_LEGACY_PATH_SHORTCUT_TICK_DIVISOR : 1)
#  define PLATFORM_MOB_SPAWN_INTERVAL_TICKS             (PLATFORM_PC_LEGACY ? PC_LEGACY_MOB_SPAWN_INTERVAL_TICKS : 1)
// End profile. 0 endermen = no End-specific cap (the global cap still applies);
// 128 teleport particles and per-tick dragon collision scans are vanilla.
#  define PLATFORM_END_MAX_ENDERMEN                     0
#  define PLATFORM_ENDERMAN_TELEPORT_PARTICLES          128
#  define PLATFORM_DRAGON_COLLISION_TICK_DIVISOR        1
// -1: the End streams like any other dimension (see WorldProvider::
// getResidentChunkRadius for what a value >= 0 means).
#  define PLATFORM_END_RESIDENT_CHUNK_RADIUS            -1
#  define PLATFORM_FORCE_FULLBRIGHT_TERRAIN             0
// Generators that can produce overhangs need the sideways pass; keep it on.
#  define PLATFORM_SEED_GAP_LIGHTING_ON_RELIGHT         1
#  define PLATFORM_SKIP_CAVE_GENERATION                 0
#  define PLATFORM_CAVE_SOURCE_RADIUS                   (PLATFORM_PC_LEGACY ? PC_LEGACY_CAVE_SOURCE_RADIUS : 8)
#  define PLATFORM_SKIP_RAVINE_GENERATION               0
#  define PLATFORM_CAVE_RARITY                          (PLATFORM_PC_LEGACY ? PC_LEGACY_CAVE_RARITY : 15)
#  define PLATFORM_FLOAT_CAVE_GENERATION                (PLATFORM_PC_LEGACY ? PC_LEGACY_FLOAT_CAVE_GENERATION : 0)
#  define PLATFORM_USE_HEIGHTMAP_TERRAIN                (PLATFORM_PC_LEGACY ? PC_LEGACY_USE_HEIGHTMAP_TERRAIN : 0)
#  define PLATFORM_FAST_SURFACE_PASS                    (PLATFORM_PC_LEGACY ? PC_LEGACY_FAST_SURFACE_PASS : 0)
#  define PLATFORM_PRECOMPUTE_INITIAL_HEIGHTMAP          (PLATFORM_PC_LEGACY ? PC_LEGACY_PRECOMPUTE_INITIAL_HEIGHTMAP : 0)
#  define PLATFORM_BATCH_INITIAL_SKYLIGHT_RENDER_UPDATES (PLATFORM_PC_LEGACY ? PC_LEGACY_BATCH_INITIAL_SKYLIGHT_RENDER_UPDATES : 0)
#  define PLATFORM_BULK_GENERATED_CHUNK_IMPORT           (PLATFORM_PC_LEGACY ? PC_LEGACY_BULK_GENERATED_CHUNK_IMPORT : 0)
// Wii overrides this to 1 in WiiWorldTuning.h; the desktop path keeps the
// vanilla per-block light jobs.
#  define PLATFORM_BATCH_POPULATION_LIGHTING             (PLATFORM_PC_LEGACY ? PC_LEGACY_BATCH_POPULATION_LIGHTING : 0)
#  define PLATFORM_POPULATION_BLOCK_WRITER                (PLATFORM_PC_LEGACY ? PC_LEGACY_POPULATION_BLOCK_WRITER : 0)
#  define PLATFORM_HEIGHTMAP_SEA_LEVEL                  (PLATFORM_PC_LEGACY ? PC_LEGACY_HEIGHTMAP_SEA_LEVEL : 64)
#  define PLATFORM_HEIGHTMAP_BASE_HEIGHT                (PLATFORM_PC_LEGACY ? PC_LEGACY_HEIGHTMAP_BASE_HEIGHT : 64)
#  define PLATFORM_HEIGHTMAP_AMPLITUDE                  (PLATFORM_PC_LEGACY ? PC_LEGACY_HEIGHTMAP_AMPLITUDE : 24)
#  define PLATFORM_HEIGHTMAP_FREEZE_TEMP                (PLATFORM_PC_LEGACY ? PC_LEGACY_HEIGHTMAP_FREEZE_TEMP : 0.5f)
#  define PLATFORM_POPULATE_WATER_SPRINGS              (PLATFORM_PC_LEGACY ? PC_LEGACY_POPULATE_WATER_SPRINGS : 50)
#  define PLATFORM_POPULATE_LAVA_SPRINGS               (PLATFORM_PC_LEGACY ? PC_LEGACY_POPULATE_LAVA_SPRINGS : 20)
#  define PLATFORM_POPULATE_DUNGEONS                   (PLATFORM_PC_LEGACY ? PC_LEGACY_POPULATE_DUNGEONS : 8)
// Vanilla populate passes the consoles switch off (see the PS2/Wii tables):
// water/lava lake rolls, the animal groups spawned with the chunk, and the
// 64 / 128 scatter attempts of WorldGenFlowers / WorldGenTallGrass.
#  define PLATFORM_POPULATE_LAKES                      1
#  define PLATFORM_POPULATE_WORLDGEN_ANIMALS           1
#  define PLATFORM_FLOWER_PLACEMENT_ATTEMPTS           64
#  define PLATFORM_TALL_GRASS_PLACEMENT_ATTEMPTS       128
#  define PLATFORM_POPULATE_TREE_BONUS                  (PLATFORM_PC_LEGACY ? PC_LEGACY_POPULATE_TREE_BONUS : 0)
// Tree and grass density knobs, see the PS2 table. -1 / -1 / 1 / 50 are the
// vanilla values.
#  define PLATFORM_POPULATE_TREES_PER_CHUNK_MAX         -1
#  define PLATFORM_POPULATE_GRASS_PER_CHUNK_MAX         -1
#  define PLATFORM_POPULATE_JUNGLE_HUGE_TREES           1
#  define PLATFORM_POPULATE_JUNGLE_VINES                50
#  define PLATFORM_POPULATE_CLAY_VEINS                 (PLATFORM_PC_LEGACY ? PC_LEGACY_POPULATE_CLAY_VEINS : 10)
#  define PLATFORM_POPULATE_DIRT_VEINS                 (PLATFORM_PC_LEGACY ? PC_LEGACY_POPULATE_DIRT_VEINS : 20)
#  define PLATFORM_POPULATE_GRAVEL_VEINS               (PLATFORM_PC_LEGACY ? PC_LEGACY_POPULATE_GRAVEL_VEINS : 10)
#  define PLATFORM_POPULATE_SNOW_PASS                  (PLATFORM_PC_LEGACY ? PC_LEGACY_POPULATE_SNOW_PASS : 1)
#  define PLATFORM_DEFERRED_POPULATE                   (PLATFORM_PC_LEGACY ? PC_LEGACY_DEFERRED_POPULATE : 0)
// Vegetation and ores decorated at generation, into the chunk buffer, instead
// of in the 2x2 populate; see ChunkProviderGenerateDecorateLocal.cpp. Off on
// desktop: it changes generated terrain (trees clipped at chunk borders).
#  define PLATFORM_CHUNK_LOCAL_DECORATION              0
#  define PLATFORM_INCREMENTAL_POPULATE                (PLATFORM_PC_LEGACY ? PC_LEGACY_INCREMENTAL_POPULATE : 0)
#  define PLATFORM_POPULATE_CHUNKS_PER_TICK            (PLATFORM_PC_LEGACY ? PC_LEGACY_POPULATE_CHUNKS_PER_TICK : 0)
#  define PLATFORM_POPULATE_STEPS_PER_TICK             (PLATFORM_PC_LEGACY ? PC_LEGACY_POPULATE_STEPS_PER_TICK : PLATFORM_POPULATE_CHUNKS_PER_TICK)
// See the PS2 branch above: 0 keeps the original stand-down on a tick that
// published a column.
#  define PLATFORM_POPULATE_STEPS_AFTER_PUBLISH        0
#  define PLATFORM_POPULATE_BUDGET_US                  (PLATFORM_PC_LEGACY ? PC_LEGACY_POPULATE_BUDGET_US : 0)
#  define PLATFORM_POPULATE_SNOW_COLUMNS_PER_STEP      (PLATFORM_PC_LEGACY ? PC_LEGACY_POPULATE_SNOW_COLUMNS_PER_STEP : 256)
#  define PLATFORM_GENERATE_MAP_FEATURES               1
#  define PLATFORM_GENERATE_SYNC_RADIUS                1
#  define PLATFORM_GENERATE_CHUNKS_PER_TICK            0
#  define PLATFORM_INCREMENTAL_CHUNK_GENERATION        0
#  define PLATFORM_GENERATION_STEPS_PER_TICK            0
#  define PLATFORM_GENERATION_BUDGET_US                 0
// Per-frame slice of the incremental generator (ChunkProvider::serviceFrameGeneration). 0 off.
#  define PLATFORM_GENERATION_STEPS_PER_FRAME           0
#  define PLATFORM_GENERATION_FRAME_BUDGET_US           0
// Shared per-frame cap over generation, populate and lighting (console only;
// see platform/world/StreamingFrameBudget.h). 0 off.
#  define PLATFORM_STREAMING_FRAME_BUDGET_US            0
#  define PLATFORM_GENERATION_SOURCE_COLUMNS_PER_STEP   0
#  define PLATFORM_STRUCTURE_SOURCE_COLUMNS_PER_STEP    0
// MetadataChunkBlock jobs are the unit World::updatingLighting() processes on
// each rendered frame.  Vanilla's 500 is appropriate when the CPU is idle; a
// console profile overrides it to keep chunk streaming from monopolising a
// frame.  The preload screen still drains the queue deliberately.
#  define PLATFORM_LIGHTING_UPDATES_PER_FRAME           (PLATFORM_PC_LEGACY ? PC_LEGACY_LIGHTING_UPDATES_PER_FRAME : 500)
// Interactive lighting burst (see World::updatingLighting). 0 off.
#  define PLATFORM_LIGHTING_INTERACTIVE_QUEUE_MAX       0
#  define PLATFORM_LIGHTING_INTERACTIVE_BURST           0
// Wall-clock ceiling on that same drain, in microseconds.  Zero disables it and
// leaves the job count as the only bound on the desktop profile. Console
// profiles can override both because a job count is a poor proxy
// for time here: one MetadataChunkBlock is a flood fill over a box, so its cost
// varies by more than an order of magnitude with what just streamed in.
#  define PLATFORM_LIGHTING_BUDGET_US                   (PLATFORM_PC_LEGACY ? PC_LEGACY_LIGHTING_BUDGET_US : 0)
#  define PLATFORM_LIGHTING_MERGE_SCAN                   (PLATFORM_PC_LEGACY ? PC_LEGACY_LIGHTING_MERGE_SCAN : 5)
// The Xbox has 64 MB: an unbounded queue doubles its vector until one
// contiguous allocation fails mid-generation (bad_alloc -> back to menu).
#  define PLATFORM_LIGHTING_QUEUE_HARD_CAP               (PLATFORM_XBOX ? 16384 : 1000000)
#  define PLATFORM_FAST_LIGHTING_CHUNK_ACCESS              (PLATFORM_PC_LEGACY ? PC_LEGACY_FAST_LIGHTING_CHUNK_ACCESS : 0)
#  define PLATFORM_FLOAT_TERRAIN_NOISE                    (PLATFORM_CONSOLE_LOW || (PLATFORM_PC_LEGACY ? PC_LEGACY_FLOAT_TERRAIN_NOISE : 0))
#  define PLATFORM_FLOAT_BIOME_NOISE                   (PLATFORM_PC_LEGACY ? PC_LEGACY_FLOAT_BIOME_NOISE : 0)
#  define PLATFORM_FAST_BIOME_SOURCE                   0
#  define PLATFORM_FLOAT_ORE_VEINS                     (PLATFORM_PC_LEGACY ? PC_LEGACY_FLOAT_ORE_VEINS : 0)
// Vanilla octave counts. See PS2_TERRAIN_DENSITY_OCTAVES/PS2_TERRAIN_SELECT_OCTAVES
// in Ps2Tuning.h for the console trade-off this overrides.
#  define PLATFORM_TERRAIN_DENSITY_OCTAVES              (PLATFORM_PC_LEGACY ? PC_LEGACY_TERRAIN_DENSITY_OCTAVES : 16)
#  define PLATFORM_TERRAIN_SELECT_OCTAVES               (PLATFORM_PC_LEGACY ? PC_LEGACY_TERRAIN_SELECT_OCTAVES : 8)
// Highest-frequency octaves left out of the 3D terrain noise. The count knobs
// above trim from the low-frequency, high-weight end and reshape the terrain;
// these trim from the other end. 0 is vanilla; see the Wii override.
#  define PLATFORM_TERRAIN_DENSITY_SKIP_FINE_OCTAVES    0
#  define PLATFORM_TERRAIN_SELECT_SKIP_FINE_OCTAVES     0
// Half-extent, in blocks, of the box around a freshly generated chunk outside
// which cached StructureStarts are dropped. 0 keeps vanilla's unbounded map;
// see MapGenStructure::trimStructureStarts and the Wii override.
#  define PLATFORM_STRUCTURE_START_RETENTION_BLOCKS     0
// Power-of-two size of MathHelper's sine table. 16 is vanilla's 65536 entries;
// low-memory/low-CPU profiles can shrink it to keep the table cache-friendly.
#  define PLATFORM_SIN_TABLE_BITS                      (PLATFORM_PC_LEGACY ? PC_LEGACY_SIN_TABLE_BITS : 16)
// PC and Wii both have double-precision hardware: the plain cast is one
// instruction there and the integer form would be slower.
#  define PLATFORM_INTEGER_FLOOR_DOUBLE               0
#  define PLATFORM_LEGACY_GUI_SCALE                    0.0
#  define PLATFORM_LEGACY_CREATE_WORLD_PANEL_WIDTH     245
#  define PLATFORM_FORCE_GUI_SCALE                     0
#  define PLATFORM_NEAR_PLANE                          0.05f
// Desktop: the F3 frame-time histogram covers a third of the screen and the
// port has better instrumentation elsewhere. Set to 1 for vanilla behaviour.
#  define PLATFORM_SHOW_LAGOMETER                      0
// Vanilla margin: sized for the occlusion-query box the desktop path uses.
#  define PLATFORM_RENDERER_AABB_MARGIN                6.0f
#  define PLATFORM_CURSOR_TEXTURE                      0
#  define PLATFORM_CURSOR_SIZE                         16
#  define PLATFORM_DYNAMIC_TEXTURE_INTERVAL_TICKS      (PLATFORM_PC_LEGACY ? PC_LEGACY_DYNAMIC_TEXTURE_INTERVAL_TICKS : 1)
#  define PLATFORM_TESSELLATOR_CONVERT_QUADS             1
#  define PLATFORM_TESSELLATOR_BUFFER_INTS               0x200000
// Normal desktop keeps exact double vertex/UV math and virtual chunk accessors.
// The Legacy PC profile opts into the already-verified low-CPU alternatives;
// world-generation precision is controlled by the dedicated Legacy knobs above.
#  define PLATFORM_FLOAT_VERTEX_MATH                     (PLATFORM_PC_LEGACY ? PC_LEGACY_FLOAT_VERTEX_MATH : 0)
#  define PLATFORM_COMPACT_TERRAIN_VERTICES               (PLATFORM_PC_LEGACY ? PC_LEGACY_COMPACT_TERRAIN_VERTICES : 0)
#  define PLATFORM_FAST_CHUNK_BLOCK_READS                (PLATFORM_PC_LEGACY ? PC_LEGACY_FAST_CHUNK_BLOCK_READS : 0)
#  define PLATFORM_FAST_BLOCK_COUNT_SCAN                 (PLATFORM_PC_LEGACY ? PC_LEGACY_FAST_BLOCK_COUNT_SCAN : 0)
#  define PLATFORM_MP_DEFERRED_CHUNKS                    0
#  define PLATFORM_MP_COMPRESSED_CHUNK_CACHE_BYTES       0u
#  define PLATFORM_MP_CHUNK_PROMOTIONS_PER_TICK          0
#  define PLATFORM_MP_MAX_DEFERRED_CHUNKS                768u
#  define PLATFORM_MP_MAX_CHANGES_PER_CHUNK              256u
#  define PLATFORM_MP_MAX_DEFERRED_CHANGES               8192u
#endif
