# Generates xbox_imports.asm: one __imp__Name@N pointer per Win32 import the
# modern CRT references, each pointing at the static _Name@N implementation
# (from XAPI or xbox_crt_shim.cpp). Input: xbox_imports.txt, one Name@N per line.
param([string]$List = "$PSScriptRoot\xbox_imports.txt", [string]$Out = "$PSScriptRoot\xbox_imports.asm")

$names = Get-Content $List | Where-Object { $_ -and -not $_.StartsWith('#') } | ForEach-Object { $_.Trim() } | Sort-Object -Unique
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('; Generated by gen_imports.ps1 - do not edit.')
[void]$sb.AppendLine('.686')
[void]$sb.AppendLine('.model flat')
[void]$sb.AppendLine('option casemap:none')
foreach ($n in $names) { [void]$sb.AppendLine("EXTERN _$($n):PROC") }
[void]$sb.AppendLine('.data')
foreach ($n in $names) {
    [void]$sb.AppendLine("PUBLIC __imp__$n")
    [void]$sb.AppendLine("__imp__$n DD _$n")
}
[void]$sb.AppendLine('END')
[IO.File]::WriteAllText($Out, $sb.ToString())
Write-Output "wrote $($names.Count) import thunks to $Out"
