#!/usr/bin/env python3
"""
Builds the Xbox controller button atlas (data/assets/gui/buttons_xbox.png) and the
matching UV table (src/net/minecraft/src/legacy/XboxButtonAtlasData.h).

The slot order follows the Ps2ButtonIcon enum, with each PS2 button replaced by the
Xbox button in the same position (see src/xbox/input/XboxInput.cpp):
  Cross/Circle/Square/Triangle -> A/B/X/Y, L1/R1 -> White/Black, L2/R2 -> LT/RT,
  L3/R3 -> stick clicks, Select/Start -> Back/Start.

The source icons are pixel art, so they are pasted at native size (no filtering)
unless one does not fit its cell. The original Xbox's White and Black buttons have
no source icon; they are drawn by recolouring the plain round button.

Usage: python scripts/xbox/make_button_atlas.py [icon folder]
"""

import os
import sys
from PIL import Image

DEFAULT_SRC = os.path.join(os.path.expanduser('~'), 'Downloads', 'minecraft', 'Minecraft.Client',
                           'Common', 'Media', 'Graphics', 'X360ControllerIcons')

ATLAS_SIZE = 256
# 5x5 cells of 51 px: 13 buttons + the four D-pad directions fit in 256x256.
CELL = 51
COLS = 5


def load(src, name):
    im = Image.open(os.path.join(src, name)).convert('RGBA')
    return im.crop(im.getbbox())


def dpad(src):
    # Each DPad image highlights one arm; the per-pixel median of the four is the
    # plain cross.
    ims = [Image.open(os.path.join(src, 'ButtonDpad%s.png' % d)).convert('RGBA') for d in 'UDLR']
    size = max(max(i.width for i in ims), max(i.height for i in ims))
    padded = []
    for im in ims:
        canvas = Image.new('RGBA', (size, size), (0, 0, 0, 0))
        canvas.paste(im, ((size - im.width) // 2, (size - im.height) // 2))
        padded.append(canvas.load())
    out = Image.new('RGBA', (size, size))
    px = out.load()
    for y in range(size):
        for x in range(size):
            samples = sorted((p[x, y] for p in padded), key=lambda c: (c[3], sum(c[:3])))
            px[x, y] = samples[1]
    return out.crop(out.getbbox())


def round_button(src, fill, rim):
    # Legend_Button_Disable is a flat grey disc with a light rim: remap the rim and
    # the fill separately by brightness.
    im = Image.open(os.path.join(src, 'Legend_Button_Disable.png')).convert('RGBA')
    px = im.load()
    for y in range(im.height):
        for x in range(im.width):
            r, g, b, a = px[x, y]
            if a == 0:
                continue
            colour = rim if (r + g + b) / 3 > 160 else fill
            px[x, y] = colour + (a,)
    return im.crop(im.getbbox())


def build(src):
    slots = [
        ('Cross (A)', load(src, 'ButtonA.png')),
        ('Circle (B)', load(src, 'ButtonB.png')),
        ('Square (X)', load(src, 'ButtonX.png')),
        ('Triangle (Y)', load(src, 'ButtonY.png')),
        ('DPad', dpad(src)),
        ('L1 (White)', round_button(src, (236, 236, 236), (80, 80, 80))),
        ('R1 (Black)', round_button(src, (28, 28, 28), (200, 200, 200))),
        ('L2 (LT)', load(src, 'ButtonLeftTrigger.png')),
        ('R2 (RT)', load(src, 'ButtonRightTrigger.png')),
        ('L3 (LS)', load(src, 'ButtonLS.png')),
        ('R3 (RS)', load(src, 'ButtonRS.png')),
        ('Select (Back)', load(src, 'ButtonBack.png')),
        ('Start', load(src, 'ButtonStart.png')),
        ('DPad Up', load(src, 'ButtonDpadU.png')),
        ('DPad Down', load(src, 'ButtonDpadD.png')),
        ('DPad Left', load(src, 'ButtonDpadL.png')),
        ('DPad Right', load(src, 'ButtonDpadR.png')),
    ]

    atlas = Image.new('RGBA', (ATLAS_SIZE, ATLAS_SIZE), (0, 0, 0, 0))
    rects = []
    for idx, (name, im) in enumerate(slots):
        limit = CELL - 2
        if im.width > limit or im.height > limit:
            scale = min(limit / im.width, limit / im.height)
            im = im.resize((max(1, round(im.width * scale)), max(1, round(im.height * scale))),
                           Image.Resampling.LANCZOS)
        cx = (idx % COLS) * CELL + (CELL - im.width) // 2
        cy = (idx // COLS) * CELL + (CELL - im.height) // 2
        atlas.paste(im, (cx, cy))
        rects.append((name, cx, cy, im.width, im.height))
    return atlas, rects


def write_header(path, rects):
    lines = [
        '// Auto-generated by scripts/xbox/make_button_atlas.py -- do not edit.',
        '// UVs into /gui/buttons_xbox.png, in Ps2ButtonIcon order.',
        '#pragma once',
        '',
        'static const Ps2ButtonPromptInfo s_xboxIconInfos[] = {',
    ]
    for name, x, y, w, h in rects:
        lines.append('    // %s: rect=(%d, %d, %d, %d)' % (name, x, y, w, h))
        lines.append('    { %d.0f / %d.0f, %d.0f / %d.0f, %d.0f / %d.0f, %d.0f / %d.0f, %d, %d },' % (
            x, ATLAS_SIZE, y, ATLAS_SIZE, x + w, ATLAS_SIZE, y + h, ATLAS_SIZE, w, h))
    lines.append('};')
    lines.append('')
    with open(path, 'w', newline='\n') as f:
        f.write('\n'.join(lines))


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SRC
    if not os.path.isdir(src):
        print('[!] Icon folder not found: %s' % src)
        return 1
    repo = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
    atlas, rects = build(src)

    out_png = os.path.join(repo, 'data', 'assets', 'gui', 'buttons_xbox.png')
    os.makedirs(os.path.dirname(out_png), exist_ok=True)
    atlas.save(out_png, optimize=True)
    print('[OK] %s (%d bytes)' % (out_png, os.path.getsize(out_png)))

    out_h = os.path.join(repo, 'src', 'net', 'minecraft', 'src', 'legacy', 'XboxButtonAtlasData.h')
    write_header(out_h, rects)
    print('[OK] %s' % out_h)

    # Built-in copy of the PNG, used when the console's data/ folder predates it
    # (the user often only copies the XBEs over).
    out_png_h = os.path.join(repo, 'src', 'net', 'minecraft', 'src', 'legacy', 'XboxButtonAtlasPng.h')
    with open(out_png, 'rb') as f:
        data = f.read()
    lines = [
        '// Auto-generated by scripts/xbox/make_button_atlas.py -- do not edit.',
        '#pragma once',
        '#include <cstddef>',
        '',
        'constexpr size_t XBOX_BUTTON_ATLAS_PNG_SIZE = %d;' % len(data),
        'inline const unsigned char s_xboxButtonAtlasPngData[] = {',
    ]
    for i in range(0, len(data), 16):
        lines.append('    ' + ', '.join('0x%02x' % b for b in data[i:i + 16]) + ',')
    lines.append('};')
    lines.append('')
    with open(out_png_h, 'w', newline='\n') as f:
        f.write('\n'.join(lines))
    print('[OK] %s' % out_png_h)
    return 0


if __name__ == '__main__':
    sys.exit(main())
