#!/usr/bin/env python3
"""
Builds the console crafting menu atlas (data/assets/legacy/crafting_icons.png)
from the Legacy Console Edition graphics, plus a copy embedded in the XBE
(src/net/minecraft/src/legacy/LegacyCraftingIconsPng.h) for consoles whose
data/ folder predates it.

Layout (256x128, native size, 48 px cells):
  row 0: structures, tools, food, armour, mechanisms
  row 1: transport, decoration, crafting arrow (32x32 at 96,48)

Usage: python scripts/xbox/make_crafting_icons.py [Graphics folder]
"""

import os
import sys
from PIL import Image

DEFAULT_SRC = os.path.join(os.path.expanduser('~'), 'Downloads', 'minecraft', 'Minecraft.Client',
                           'Common', 'Media', 'Graphics')

ICONS = ['icon_structures', 'icon_tools', 'icon_food', 'icon_armour', 'icon_mechanisms',
         'icon_transport', 'icon_decoration']


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SRC
    if not os.path.isdir(src):
        print('[!] Folder not found: %s' % src)
        return 1
    atlas = Image.new('RGBA', (256, 128), (0, 0, 0, 0))
    for i, name in enumerate(ICONS):
        im = Image.open(os.path.join(src, 'CraftIcons', name + '.png')).convert('RGBA')
        atlas.paste(im, ((i % 5) * 48, (i // 5) * 48))
    arrow = Image.open(os.path.join(src, 'Arrow_Small_Off.png')).convert('RGBA')
    atlas.paste(arrow, (96, 48))

    repo = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
    out_png = os.path.join(repo, 'data', 'assets', 'legacy', 'crafting_icons.png')
    os.makedirs(os.path.dirname(out_png), exist_ok=True)
    atlas.save(out_png, optimize=True)
    print('[OK] %s (%d bytes)' % (out_png, os.path.getsize(out_png)))

    with open(out_png, 'rb') as f:
        data = f.read()
    out_h = os.path.join(repo, 'src', 'net', 'minecraft', 'src', 'legacy', 'LegacyCraftingIconsPng.h')
    lines = [
        '// Auto-generated by scripts/xbox/make_crafting_icons.py -- do not edit.',
        '#pragma once',
        '#include <cstddef>',
        '',
        'constexpr size_t LEGACY_CRAFTING_ICONS_PNG_SIZE = %d;' % len(data),
        'inline const unsigned char s_legacyCraftingIconsPngData[] = {',
    ]
    for i in range(0, len(data), 16):
        lines.append('    ' + ', '.join('0x%02x' % b for b in data[i:i + 16]) + ',')
    lines += ['};', '']
    with open(out_h, 'w', newline='\n') as f:
        f.write('\n'.join(lines))
    print('[OK] %s' % out_h)
    return 0


if __name__ == '__main__':
    sys.exit(main())
