#pragma once

#include <string>
#include <vector>
#include "java/Random.h"
#include "EnumAction.h"
#include "EnumRarity.h"

class ItemStack;
class EntityPlayer;
class World;
class EntityLiving;
class Entity;
class Block;
class NBTTagCompound;
class MovingObjectPosition;

class Item {
public:
    Item(int id);
    virtual ~Item() = default;

    virtual Item* setIconIndex(int icon);
    virtual Item* setMaxStackSize(int size);
    virtual Item* setIconCoord(int x, int y);
    virtual int getIconFromDamage(int damage);
    int getIconIndex(ItemStack* itemstack);
    virtual bool onItemUse(ItemStack* itemstack, EntityPlayer* entityplayer, World* world, int i, int j, int k, int l);
    virtual float getStrVsBlock(ItemStack* itemstack, Block* block);
    virtual ItemStack* onItemRightClick(ItemStack* itemstack, World* world, EntityPlayer* entityplayer);
    virtual ItemStack* onFoodEaten(ItemStack* itemstack, World* world, EntityPlayer* entityplayer);
    virtual EnumAction getItemUseAction(ItemStack* itemstack);
    virtual int getMaxItemUseDuration(ItemStack* itemstack);
    virtual void onPlayerStoppedUsing(ItemStack* itemstack, World* world, EntityPlayer* entityplayer, int timeLeft);
    int getItemStackLimit();
    virtual int getMetadata(int damage);
    virtual int getPlacedBlockMetadata(int damage);
    bool getHasSubtypes();
    Item* setHasSubtypes(bool flag);
    int getMaxDamage();
    Item* setMaxDamage(int damage);
    bool isDamageable();
    bool isDamagable();
    virtual bool hitEntity(ItemStack* itemstack, EntityLiving* entityliving, EntityLiving* entityliving1);
    virtual bool onBlockDestroyed(ItemStack* itemstack, int i, int j, int k, int l, EntityLiving* entityliving);
    virtual int getDamageVsEntity(Entity* entity);
    virtual bool canHarvestBlock(Block* block);
    virtual void useItemOnEntity(ItemStack* itemstack, EntityLiving* entityliving);
    virtual void saddleEntity(ItemStack* itemstack, EntityLiving* entityliving);
    Item* setFull3D();
    virtual bool isFull3D();
    virtual bool shouldRotateAroundWhenRendering();
    Item* setItemName(const char* name);
    virtual std::string getItemName();
    virtual std::string getItemNameIS(ItemStack* itemstack);
    virtual std::string getLocalItemName(ItemStack* itemstack);
    virtual std::string getItemDisplayName(ItemStack* itemstack);
    virtual void addInformation(ItemStack* itemstack, std::vector<std::string>& information);
    Item* setContainerItem(Item* item);
    Item* getContainerItem();
    virtual bool doesContainerItemLeaveCraftingGrid(ItemStack* itemstack);
    bool hasContainerItem();
    std::string getStatName();
    virtual int getColorFromDamage(int damage);
    virtual int getColorFromDamage(int damage, int renderPass);
    virtual void onUpdate(ItemStack* itemstack, World* world, Entity* entity, int i, bool flag);
    virtual void onCreated(ItemStack* itemstack, World* world, EntityPlayer* entityplayer);
    virtual bool hasEffect(ItemStack* itemstack);
    virtual const EnumRarity& getRarity(ItemStack* itemstack);
    virtual bool isItemTool(ItemStack* itemstack);
    virtual int getItemEnchantability();
    virtual bool func_46056_k();
    Item* setPotionEffect(const std::string& effect);
    const std::string& getPotionEffect() const;
    bool isPotionIngredient() const;
    virtual bool func_46058_c();
    virtual int func_46057_a(int damage, int renderPass);

    static void initItems();
    static void cleanup();

#if defined(PS2_PLATFORM) || defined(WII_PLATFORM) || defined(XBOX_PLATFORM)
    static constexpr int ITEM_LIST_SIZE = 4096;
#else
    static constexpr int ITEM_LIST_SIZE = 32000;
#endif
    static Item* itemsList[ITEM_LIST_SIZE];
    static Random itemRand;

    static Item* shovelSteel;
    static Item* pickaxeSteel;
    static Item* axeSteel;
    static Item* flintAndSteel;
    static Item* appleRed;
    static Item* bow;
    static Item* arrow;
    static Item* coal;
    static Item* diamond;
    static Item* ingotIron;
    static Item* ingotGold;
    static Item* swordSteel;
    static Item* swordWood;
    static Item* shovelWood;
    static Item* pickaxeWood;
    static Item* axeWood;
    static Item* swordStone;
    static Item* shovelStone;
    static Item* pickaxeStone;
    static Item* axeStone;
    static Item* swordDiamond;
    static Item* shovelDiamond;
    static Item* pickaxeDiamond;
    static Item* axeDiamond;
    static Item* stick;
    static Item* bowlEmpty;
    static Item* bowlSoup;
    static Item* swordGold;
    static Item* shovelGold;
    static Item* pickaxeGold;
    static Item* axeGold;
    static Item* silk;
    static Item* feather;
    static Item* gunpowder;
    static Item* hoeWood;
    static Item* hoeStone;
    static Item* hoeSteel;
    static Item* hoeDiamond;
    static Item* hoeGold;
    static Item* seeds;
    static Item* wheat;
    static Item* bread;
    static Item* helmetLeather;
    static Item* plateLeather;
    static Item* legsLeather;
    static Item* bootsLeather;
    static Item* helmetChain;
    static Item* plateChain;
    static Item* legsChain;
    static Item* bootsChain;
    static Item* helmetSteel;
    static Item* plateSteel;
    static Item* legsSteel;
    static Item* bootsSteel;
    static Item* helmetDiamond;
    static Item* plateDiamond;
    static Item* legsDiamond;
    static Item* bootsDiamond;
    static Item* helmetGold;
    static Item* plateGold;
    static Item* legsGold;
    static Item* bootsGold;
    static Item* flint;
    static Item* porkRaw;
    static Item* porkCooked;
    static Item* painting;
    static Item* appleGold;
    static Item* sign;
    static Item* doorWood;
    static Item* bucketEmpty;
    static Item* bucketWater;
    static Item* bucketLava;
    static Item* minecartEmpty;
    static Item* saddle;
    static Item* doorSteel;
    static Item* redstone;
    static Item* snowball;
    static Item* boat;
    static Item* leather;
    static Item* bucketMilk;
    static Item* brick;
    static Item* clay;
    static Item* reed;
    static Item* paper;
    static Item* book;
    static Item* slimeBall;
    static Item* minecartCrate;
    static Item* minecartPowered;
    static Item* egg;
    static Item* compass;
    static Item* fishingRod;
    static Item* pocketSundial;
    static Item* lightStoneDust;
    static Item* fishRaw;
    static Item* fishCooked;
    static Item* dyePowder;
    static Item* bone;
    static Item* sugar;
    static Item* cake;
    static Item* bed;
    static Item* redstoneRepeater;
    static Item* cookie;
    static Item* mapItem;
    static Item* shears;
    static Item* melon;
    static Item* pumpkinSeeds;
    static Item* melonSeeds;
    static Item* netherStalkSeeds;
    static Item* beefRaw;
    static Item* beefCooked;
    static Item* chickenRaw;
    static Item* chickenCooked;
    static Item* rottenFlesh;
    static Item* enderPearl;
    static Item* blazeRod;
    static Item* ghastTear;
    static Item* goldNugget;
    static Item* potion;
    static Item* glassBottle;
    static Item* spiderEye;
    static Item* fermentedSpiderEye;
    static Item* blazePowder;
    static Item* magmaCream;
    static Item* brewingStand;
    static Item* cauldron;
    static Item* eyeOfEnder;
    static Item* speckledMelon;
    static Item* monsterPlacer;
    static Item* expBottle;
    static Item* fireballCharge;
    static Item* record13;
    static Item* recordCat;
    static Item* recordBlocks;
    static Item* recordChirp;
    static Item* recordFar;
    static Item* recordMall;
    static Item* recordMellohi;
    static Item* recordStal;
    static Item* recordStrad;
    static Item* recordWard;
    static Item* record11;

    int shiftedIndex;

protected:
    int maxStackSize;
    int maxDamage;
    int iconIndex = 0;
    bool bFull3D;
    bool hasSubtypes;
    Item* containerItem;
    const char* itemName = nullptr;
    std::string potionEffect;

    MovingObjectPosition* getMovingObjectPositionFromPlayer(World* world, EntityPlayer* player, bool includeLiquids);
};
